### ISSUE TITLE
[pipermail] Certificate verification error with some lists

### ISSUE THREAD

**Issue by albertinisg** [chaoss/grimoirelab-perceval#104]
When trying to fetch some pipermail archives, a certificate error is returned during the handshake:
```bash
$ perceval pipermail https://lists.projectatomic.io/projectatomic-archives/atomic-devel/
[2016-12-28 15:26:29,747] - Sir Perceval is on his quest.
[2016-12-28 15:26:29,749] - Looking for messages from 'https://lists.projectatomic.io/projectatomic-archives/atomic-devel/' since 1970-01-01 00:00:00+00:00
[2016-12-28 15:26:29,749] - Downloading mboxes from 'https://lists.projectatomic.io/projectatomic-archives/atomic-devel/' to since 1970-01-01 00:00:00+00:00
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 559, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 786, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 252, in connect
    ssl_version=resolved_ssl_version)
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 305, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.5/ssl.py", line 385, in wrap_socket
    _context=self)
  File "/usr/lib/python3.5/ssl.py", line 760, in __init__
    self.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 996, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 641, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:720)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 588, in urlopen
    raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:720)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.5.0.dev2-py3.5.egg/perceval/backends/core/pipermail.py", line 149, in run
    for message in messages:
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.5.0.dev2-py3.5.egg/perceval/backend.py", line 192, in decorator
    for data in func(self, *args, **kwargs):
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.5.0.dev2-py3.5.egg/perceval/backends/core/pipermail.py", line 91, in fetch
    mailing_list.fetch(from_date=from_date)
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.5.0.dev2-py3.5.egg/perceval/backends/core/pipermail.py", line 214, in fetch
    r = requests.get(self.url)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 447, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:720)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/perceval", line 4, in <module>
    __import__('pkg_resources').run_script('perceval==0.5.0.dev2', 'perceval')
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 746, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 1501, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.5.0.dev2-py3.5.egg/EGG-INFO/scripts/perceval", line 179, in <module>
    main()
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.5.0.dev2-py3.5.egg/EGG-INFO/scripts/perceval", line 100, in main
    cmd.run()
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.5.0.dev2-py3.5.egg/perceval/backends/core/pipermail.py", line 154, in run
    raise RuntimeError(str(e))
RuntimeError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:720)
```
Something similar happened with Jira's backend, so there I've implemented an option to enable [insecure requests](https://github.com/grimoirelab/perceval/blob/master/perceval/backends/core/jira.py#L435) or add a valid [PEM key](https://github.com/grimoirelab/perceval/blob/master/perceval/backends/core/jira.py#L437).

As this is something that probably extends to other backends, how about adding a `--insecure` parameter as general argument? I don't like the idea of making insecure requests by default when its not needed.

**Comment by sduenas** [comment]
This is not an issue anymore. Users can use the general flag `--no-ssl-verify` to avoid SSL certificates validation.
