### ISSUE TITLE
[mbox] Error when parsing emails

### ISSUE THREAD

**Issue by sachinkamath** [chaoss/grimoirelab-perceval#326]
### Background
I was running `p2o` on mbox files I had downloaded previously by Perceval.Perceval crashed in the middle with a traceback.

Not sure if it is a bug in perceval, but filing it here anyway so that someone can take a look

Traceback:

```
2018-02-17 08:36:16,846 Error feeding ocean from mbox (**URL redacted**): Compressed file ended before the end-of-stream marker was r
eached
Traceback (most recent call last):
  File "/home/skamath/.local/lib/python3.6/site-packages/grimoire_elk/arthur.py", line 196, in feed_backend
    ocean_backend.feed()
  File "/home/skamath/.local/lib/python3.6/site-packages/grimoire_elk/ocean/elastic.py", line 204, in feed
    self.feed_items(items)
  File "/home/skamath/.local/lib/python3.6/site-packages/grimoire_elk/ocean/elastic.py", line 214, in feed_items
    for item in items:
  File "/home/skamath/.local/lib/python3.6/site-packages/perceval/backend.py", line 360, in decorator
    for data in func(self, *args, **kwargs):
  File "/home/skamath/.local/lib/python3.6/site-packages/perceval/backends/core/mbox.py", line 94, in fetch
    for message in messages:
  File "/home/skamath/.local/lib/python3.6/site-packages/perceval/backends/core/mbox.py", line 138, in _fetch_and_parse_messages
    raise e
  File "/home/skamath/.local/lib/python3.6/site-packages/perceval/backends/core/mbox.py", line 108, in _fetch_and_parse_messages
    tmp_path = self._copy_mbox(mbox)
  File "/home/skamath/.local/lib/python3.6/site-packages/perceval/backends/core/mbox.py", line 153, in _copy_mbox
    for l in f_in:
  File "/usr/lib64/python3.6/gzip.py", line 374, in readline
    return self._buffer.readline(size)
  File "/usr/lib64/python3.6/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/lib64/python3.6/gzip.py", line 482, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached

```

**Comment by valeriocos** [comment]
Thank you for reporting this issue @sachinkamath
This bug should not appear if you use the code in the master branch. Which version of perceval are you using?
If you want a quick workaround, you can patch your code like this: https://github.com/chaoss/grimoirelab-perceval/pull/311/files

**Comment by jgbarah** [comment]
Thanks, @valeriocos. It is very likely that @sachinkamath is trying the latest version in pypi. Am I right, @sachinkamath. If that's the case, expect a new release of packages in pypi during this week, whcih should hopefully fix this bug.

**Comment by sachinkamath** [comment]
Hi @valeriocos and @jgbarah ,

To test what you said, I removed the existing perceval version just to be sure and installed it from the latest master using `pip3 install --user https://github.com/chaoss/grimoirelab-perceval/tarball/master`

I re-ran p2o and the issue seems to persist.

**Comment by sachinkamath** [comment]
Update : Sorry, it's fixed. I was outside of my virtualenv and I had also installed it locally without using virtualenv at first and forgot to remove it later. 

Installing from the master branch works :) Thank you @valeriocos and @jgbarah  💃

**Comment by sduenas** [comment]
Closing it as is already fixed.
