### ISSUE TITLE
None category not valid for GitHub

### ISSUE THREAD

**Issue by VertexC** [chaoss/grimoirelab-perceval#354]
I was going through tutorial for perceval but found the examples didn't work in my case.
I used it under virtual environment.

```bash
$ perceval github grimoirelab perceval
[2018-03-15 01:41:58,108] - Sir Perceval is on his quest.
Traceback (most recent call last):
  File "/home/bowenc/venvs/grimoirelab/lib/python3.5/site-packages/perceval/backend.py", line 378, in run
    for item in items:
  File "/home/bowenc/venvs/grimoirelab/lib/python3.5/site-packages/perceval/backend.py", line 482, in fetch
    raise e
  File "/home/bowenc/venvs/grimoirelab/lib/python3.5/site-packages/perceval/backend.py", line 476, in fetch
    for item in items:
  File "/home/bowenc/venvs/grimoirelab/lib/python3.5/site-packages/perceval/backend.py", line 121, in fetch
    raise BackendError(cause=cause)
perceval.errors.BackendError: None category not valid for GitHub

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bowenc/venvs/grimoirelab/bin/perceval", line 193, in <module>
    main()
  File "/home/bowenc/venvs/grimoirelab/bin/perceval", line 111, in main
    cmd.run()
  File "/home/bowenc/venvs/grimoirelab/lib/python3.5/site-packages/perceval/backend.py", line 385, in run
    raise RuntimeError(str(e))
RuntimeError: None category not valid for GitHub
```

Same situation for all backends. Anyone can help?

**Comment by valeriocos** [comment]
Hi @VertexC, thank you for reporting this error.

The PR https://github.com/chaoss/grimoirelab-perceval/pull/353 should fix this error. In the meanwhile, you can pass the category to the parser. The category for the github backend is "issue" (you can find the categories of each backend at the beginning of the corresponding python file, after the import section, in [perceval/backends/core](https://github.com/chaoss/grimoirelab-perceval/tree/master/perceval/backends/core))
```
perceval github grimoirelab perceval --from-date=2017-03-01 --category=issue --api-token=XXXX
```

**Comment by sduenas** [comment]
It's fixed in `master` branch but we still need to generate a new pip package with this fix.
