### ISSUE TITLE
[pipermail] Strange error getting mboxes 

### ISSUE THREAD

**Issue by jsmanrique** [chaoss/grimoirelab-perceval#358]
I am trying to analyze [a set of mailing lists](https://lists.ubuntu.com/) and it seems all of them have public archives. For example:
https://lists.ubuntu.com/archives/xubuntu-users/

But, I am having issues getting the data:
```
$ perceval pipermail --category message https://lists.ubuntu.com/archives/xubuntu-users/
[2018-03-19 18:15:43,255] - Sir Perceval is on his quest.
[2018-03-19 18:15:43,257] - Looking for messages from 'https://lists.ubuntu.com/archives/xubuntu-users/' since 1970-01-01 00:00:00+00:00
[2018-03-19 18:15:43,257] - Downloading mboxes from 'https://lists.ubuntu.com/archives/xubuntu-users/' to since 1970-01-01 00:00:00+00:00
Traceback (most recent call last):
  File "/home/jsmanrique/grimoirelab/venvs/perceval/lib/python3.5/site-packages/perceval/backend.py", line 378, in run
    for item in items:
  File "/home/jsmanrique/grimoirelab/venvs/perceval/lib/python3.5/site-packages/perceval/backend.py", line 482, in fetch
    raise e
  File "/home/jsmanrique/grimoirelab/venvs/perceval/lib/python3.5/site-packages/perceval/backend.py", line 476, in fetch
    for item in items:
  File "/home/jsmanrique/grimoirelab/venvs/perceval/lib/python3.5/site-packages/perceval/backend.py", line 129, in fetch
    for item in self.fetch_items(category, **kwargs):
  File "/home/jsmanrique/grimoirelab/venvs/perceval/lib/python3.5/site-packages/perceval/backends/core/pipermail.py", line 103, in fetch_items
    mailing_list.fetch(from_date=from_date)
  File "/home/jsmanrique/grimoirelab/venvs/perceval/lib/python3.5/site-packages/perceval/backends/core/pipermail.py", line 222, in fetch
    success = self._download_archive(l, filepath)
  File "/home/jsmanrique/grimoirelab/venvs/perceval/lib/python3.5/site-packages/perceval/backends/core/pipermail.py", line 294, in _download_archive
    r.raise_for_status()
  File "/home/jsmanrique/grimoirelab/venvs/perceval/lib/python3.5/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://lists.ubuntu.com/archives/xubuntu-users/../xubuntu-users.mbox/xubuntu-users.mbox
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/jsmanrique/grimoirelab/venvs/perceval/bin/perceval", line 193, in <module>
    main()
  File "/home/jsmanrique/grimoirelab/venvs/perceval/bin/perceval", line 111, in main
    cmd.run()
  File "/home/jsmanrique/grimoirelab/venvs/perceval/lib/python3.5/site-packages/perceval/backend.py", line 383, in run
    raise RuntimeError(str(e))
RuntimeError: 403 Client Error: Forbidden for url: https://lists.ubuntu.com/archives/xubuntu-users/../xubuntu-users.mbox/xubuntu-users.mbox
```

If I try to download the `.mbox` file with wget or curl, I get a 403 error. But I can download it with my web browser.

What am I doing wrong?

**Comment by sduenas** [comment]
You aren't doing anything wrong. That's a bug caused because https://lists.ubuntu.com/archives/xubuntu-users/ contains a link to the URL that has the problem. `pipermail` backend parsers all the URLs of a webpage and keeps those that are links to `mboxes` files.
