### ISSUE TITLE
SQLite error when running from SirMordred

### ISSUE THREAD

**Issue by jgbarah** [chaoss/grimoirelab-perceval#421]
When producing the dashboard with the `grimoirelab/full` container, when it enters incremental mode, I see the following error:

```
Enrichment for git: starting...
Exception ignored in: <bound method Archive.__del__ of <perceval.archive.Archive object at 0x7f1498f6fba8>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/perceval/archive.py", line 104, in __del__
    conn.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 139726740801280 and this is thread id 139726489462528
Exception ignored in: <bound method Archive.__del__ of <perceval.archive.Archive object at 0x7f149991e5c0>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/perceval/archive.py", line 104, in __del__
    conn.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 139726740801280 and this is thread id 139726489462528
Enrichment for git: finished after 00:00:04 hours
```

I'm not sure if it happens every time I run it, but I've seen the errors several times. Any clue about what could be happening, to narrow the problem? Should I open this in SirMordred instead / in addition to this issue?

**Comment by sduenas** [comment]
I think this is already fixed. We also changed the way the cache works and we normally recommend not to use the archive.
So, I'm gonna close it. Feel free to open it again if you find the error.
