### ISSUE TITLE
[bugzilla xmlrpc] [feature/bug] how to handle perceval bugzilla-xmlrpc authentification and client

### ISSUE THREAD

**Issue by MalloZup** [chaoss/grimoirelab-perceval#431]
# how to reproduce:
( this issue was modified)

Basically we need a backend to access bugzilla xmlrpc api.

**Comment by sduenas** [comment]
I haven't check it but for Bugzilla >= 4 we recommend to use `buzillarest` instead of `bugzilla` backend. That backend supports authentication too. In any case, I'll check this error but I'm afraid the authentication method was changed for > 3 versions.

**Comment by MalloZup** [comment]
using rest:

```bash
perceval bugzillarest 'https://bugzilla.opensuse.org/index.cgi' --backend-user dmaiocchi --backend-password 'SomewhereOverTheRainbow' --from-date '2016-01-01'
```
```python
[2018-09-05 18:49:16,204] - Sir Perceval is on his quest.
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/perceval/backend.py", line 382, in run
    for item in items:
  File "/usr/lib/python3.4/site-packages/perceval/backend.py", line 492, in fetch
    raise e
  File "/usr/lib/python3.4/site-packages/perceval/backend.py", line 486, in fetch
    for item in items:
  File "/usr/lib/python3.4/site-packages/perceval/backend.py", line 125, in fetch
    self.client = self._init_client()
  File "/usr/lib/python3.4/site-packages/perceval/backends/core/bugzillarest.py", line 171, in _init_client
    archive=self.archive, from_archive=from_archive)
  File "/usr/lib/python3.4/site-packages/perceval/backends/core/bugzillarest.py", line 303, in __init__
    self.login(user, password)
  File "/usr/lib/python3.4/site-packages/perceval/backends/core/bugzillarest.py", line 317, in login
    r = self.call(self.RLOGIN, params)
  File "/usr/lib/python3.4/site-packages/perceval/backends/core/bugzillarest.py", line 420, in call
    result = r.json()
  File "/usr/lib/python3.4/site-packages/requests/models.py", line 896, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib64/python3.4/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.4/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib64/python3.4/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
```

I will check more when i have time if you have any hint is welcome :+1:

**Comment by MalloZup** [comment]
@sduenas  so i just discovered that the bugzilla in quesiton use 

"mybugzilla/xmlrpc.cgi".

And i don't see any xmlrpc client/backend in perceval.

Imho we have 2 solutions:

1) implement xmlrpc backend for perceval
2) use some existing backend and prepare needed data from there on to be passed to kibiter etc.

For that i think i need to know which data and the format should look like, is there any doc about this?

what do you think in general? tia

**Comment by sduenas** [comment]
I don't think we're going to implement this in the short/mid-term. I'm closing this ticket.
