### ISSUE TITLE
Issue with a "ghost" GitHub user that doesn't return user data

### ISSUE THREAD

**Issue by GregSutcliffe** [chaoss/grimoirelab-perceval#459]
I'm indexing a Github repo, and I'm hitting an error with a specific PR:

```
2018-11-19 14:16:15,519 Get GitHub paginated items from https://api.github.com/repos/ansible/ansible/pulls/41441/comments
2018-11-19 14:16:15,637 Archiving e85fc673592f5e97d55c0287dbffc6478ada41ff with https://api.github.com/repos/ansible/ansible/pulls/41441/comments {'per_page': 100, 'direction': 'asc', 'sort':
 'updated'} None in /root/.perceval/archives/ad/54899fcabb4a159c4573e122139d39.sqlite3
2018-11-19 14:16:15,641 e85fc673592f5e97d55c0287dbffc6478ada41ff data archived in /root/.perceval/archives/ad/54899fcabb4a159c4573e122139d39.sqlite3
2018-11-19 14:16:15,641 Rate limit: 4611
2018-11-19 14:16:15,641 Rate limit reset: 3532.0
2018-11-19 14:16:15,642 Error feeding ocean from github (https://github.com/ansible/ansible): 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/opt/grimoirelab/lib/python3.5/site-packages/grimoire_elk/elk.py", line 201, in feed_backend
    ocean_backend.feed(from_date, category=category)  
  File "/opt/grimoirelab/lib/python3.5/site-packages/grimoire_elk/raw/elastic.py", line 202, in feed
    self.feed_items(items)
  File "/opt/grimoirelab/lib/python3.5/site-packages/grimoire_elk/raw/elastic.py", line 211, in feed_items
    for item in items:
  File "/opt/grimoirelab/lib/python3.5/site-packages/perceval/backend.py", line 127, in fetch
    for item in self.fetch_items(category, **kwargs): 
  File "/opt/grimoirelab/lib/python3.5/site-packages/perceval/backends/core/github.py", line 257, in __fetch_pull_requests
    pull[field + '_data'] = self.__get_pull_review_comments(pull['number'])
  File "/opt/grimoirelab/lib/python3.5/site-packages/perceval/backends/core/github.py", line 373, in __get_pull_review_comments
    comment['user_data'] = self.__get_user(comment['user']['login'])
TypeError: 'NoneType' object is not subscriptable
2018-11-19 14:16:15,658 Done github
2018-11-19 14:16:15,659 Backend feed completed
```

It appears to be an issue with a specific user that isn't returning data from the API.

**Comment by GregSutcliffe** [comment]
I have a workaround:

```
diff --git a/backends/core/github.py.orig b/backends/core/github.py
index 2ef7e66..511bd50 100644
--- a/backends/core/github.py.orig
+++ b/backends/core/github.py
@@ -370,6 +370,12 @@ class GitHub(Backend):
 
             for comment in json.loads(raw_comments):
                 comment_id = comment.get('id')
+                if 'user' not in comment:
+                    logger.warning("No user: Skipping comment ....")
+                    continue
+                if comment['user'] is None:
+                    logger.warning("NoneType user: Skipping comment ....")
+                    continue
                 comment['user_data'] = self.__get_user(comment['user']['login'])
                 comment['reactions_data'] = \
                     self.__get_pull_review_comment_reactions(comment_id, comment['reactions']['total_count'])
```

I'm no Python expert, so it may be a bit hacky, but if this seems reasonable I'll happily submit a PR

**Comment by valeriocos** [comment]
thank you @GregSutcliffe . @sduenas do you agree about submitting this PR?

WRT the PR I would merge the two if statements in one, for instance:
```
comment_id = comment.get('id')
                
if 'user' not in comment or not comment['user']:
    logger.warning("Missing user info: Skipping comment %s in issue %s", 
                             comment_id, pr_number)
    continue
                
comment['user_data'] = self.__get_user(comment['user']['login'])
```
If you submit the PR, please increment by one the last number of the variable `version` at the beginning of the file (since the PR targets minor change)

Generally, a PR should come with some related test code. You could add to the file https://github.com/chaoss/grimoirelab-perceval/blob/master/tests/data/github/github_request_pull_request_2_comments the two comments below. The former contains an empty user and the latter doesn't have the user attribute.
```
{
        "_links": {
            "html": {
                "href": "https://github.com/zhquan_example/repo/pull/1#discussion_r46719268"
            },
            "pull_request": {
                "href": "https://api.github.com/repos/zhquan_example/repo/pulls/2"
            },
            "self": {
                "href": "https://api.github.com/repos/zhquan_example/repo/pulls/comments/2"
            }
        },
        "author_association": "OWNER",
        "body": "It shouldn't be there any spaces around keywords and assignments.\nFor instance : `url=None`. The same mistake can be found in other parts of this code.\n",
        "commit_id": "cc134f32fa8c518abe5f0501836af69741b25a64",
        "created_at": "2015-12-04T19:09:29Z",
        "diff_hunk": "...",
        "html_url": "https://github.com/zhquan_example/repo/pull/1#discussion_r46719268",
        "id": 5,
        "original_commit_id": "b030dbf53d3ecaae2f080018073c9bdafb6b4166",
        "original_position": 46,
        "path": "perceval/backends/gerrit.py",
        "position": null,
        "pull_request_review_id": null,
        "pull_request_url": "https://api.github.com/repos/zhquan_example/repo/pulls/2",
        "reactions": {
            "+1": 0,
            "-1": 0,
            "confused": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "total_count": 0,
            "url": "https://api.github.com/repos/zhquan_example/repo/pulls/comments/2/reactions"
        },
        "updated_at": "2015-12-22T12:03:01Z",
        "url": "https://api.github.com/repos/zhquan_example/repo/pulls/comments/2",
        "user": {}
    },
    {
        "_links": {
            "html": {
                "href": "https://github.com/zhquan_example/repo/pull/1#discussion_r46719268"
            },
            "pull_request": {
                "href": "https://api.github.com/repos/zhquan_example/repo/pulls/2"
            },
            "self": {
                "href": "https://api.github.com/repos/zhquan_example/repo/pulls/comments/2"
            }
        },
        "author_association": "OWNER",
        "body": "It shouldn't be there any spaces around keywords and assignments.\nFor instance : `url=None`. The same mistake can be found in other parts of this code.\n",
        "commit_id": "cc134f32fa8c518abe5f0501836af69741b25a64",
        "created_at": "2015-12-04T19:09:29Z",
        "diff_hunk": "...",
        "html_url": "https://github.com/zhquan_example/repo/pull/1#discussion_r46719268",
        "id": 6,
        "original_commit_id": "b030dbf53d3ecaae2f080018073c9bdafb6b4166",
        "original_position": 46,
        "path": "perceval/backends/gerrit.py",
        "position": null,
        "pull_request_review_id": null,
        "pull_request_url": "https://api.github.com/repos/zhquan_example/repo/pulls/2",
        "reactions": {
            "+1": 0,
            "-1": 0,
            "confused": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "total_count": 0,
            "url": "https://api.github.com/repos/zhquan_example/repo/pulls/comments/2/reactions"
        },
        "updated_at": "2015-12-22T12:03:01Z",
        "url": "https://api.github.com/repos/zhquan_example/repo/pulls/comments/2"
    }
```
You should modify the test code with something like this:
- at line https://github.com/chaoss/grimoirelab-perceval/blob/master/tests/test_github.py#L40, import the logger of the GitHub Perceval backend
 ```
from perceval.backends.core.github import (logger,
                                            GitHub, ...
```

- at line https://github.com/chaoss/grimoirelab-perceval/blob/master/tests/test_github.py#L589 checks that the log messages are triggered/shown correctly

```
github = GitHub("zhquan_example", "repo", "aaa")

with self.assertLogs(logger) as cm:
            pulls = [pulls for pulls in github.fetch(category=CATEGORY_PULL_REQUEST, from_date=None)]

           self.assertEqual(cm.output[0],
                             'WARNING:perceval.backends.core.github:Missing user info: Skipping comment 5 in issue 2')
          self.assertEqual(cm.output[1],
                             'WARNING:perceval.backends.core.github:Missing user info: Skipping comment 6 in issue 2')

self.assertEqual(len(pulls), 2)
```

**Comment by sduenas** [comment]
In my opinion, we should keep the comment and set the user to `None` or similar. A warning message should be also written.

**Comment by GregSutcliffe** [comment]
Thanks both. Keeping the comment seems reasonable, there may be uses for the body even without the user data. I'll see what I can do, but it will have to wait to next week :)
