### ISSUE TITLE
Error related to autoprofile

### ISSUE THREAD

**Issue by jgbarah** [chaoss/grimoirelab-perceval#465]
When launching the last SortingHat from SirMordred, I get the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/sortinghat", line 207, in <module>
    code = main()
  File "/usr/local/bin/sortinghat", line 101, in main
    code = cmd.run(*args.cmd_args)
  File "/usr/local/lib/python3.5/dist-packages/sortinghat/cmd/autoprofile.py", line 76, in run
    code = self.autocomplete(sources)
  File "/usr/local/lib/python3.5/dist-packages/sortinghat/cmd/autoprofile.py", line 106, in autocomplete
    if email_pattern.match(name):
TypeError: expected string or bytes-like object
2018-12-15 18:02:15,947 - sirmordred.task_identities - ERROR - [sortinghat] Error in command ['sortinghat', '-u', 'grimoirelab', '-p', '', '--host', 'localhost', '-d', 'grimoirelab_sh', 'autoprofile', 'CHAOSS:manual', 'git', 'github']
```

This happens with the default `grimoirelab/full` container, when run as:

```
docker run -p 127.0.0.1:5601:5601 -v $(pwd)/mordred-credentials-jgb.cfg:/override.cfg -t grimoirelab/full
```

The problem happens after a little while, apparently when   the first data source is done, and autoprofile is fired to update the SortingHat database.

**Comment by sduenas** [comment]
This is an error in SortingHat not in Perceval. Would you open it there?
