### ISSUE TITLE
Perceval GitHub fails to process kubernetes/kubernetes repo

### ISSUE THREAD

**Issue by lukaszgryglicki** [chaoss/grimoirelab-perceval#474]
See `time ./bin/perceval github kubernetes kubernetes --category issue -t "`cat /etc/github/oauth`" --sleep-for-rate --from-date 2014-01-01` output:
```
[2019-01-17 19:20:18,795] - Sir Perceval is on his quest.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/perceval/backend.py", line 385, in run
    for item in items:
  File "/usr/local/lib/python3.6/dist-packages/perceval/backend.py", line 498, in fetch
    raise e
  File "/usr/local/lib/python3.6/dist-packages/perceval/backend.py", line 492, in fetch
    for item in items:
  File "/usr/local/lib/python3.6/dist-packages/perceval/backend.py", line 127, in fetch
    for item in self.fetch_items(category, **kwargs):
  File "/usr/local/lib/python3.6/dist-packages/perceval/backends/core/github.py", line 217, in __fetch_issues
    for raw_issues in issues_groups:
  File "/usr/local/lib/python3.6/dist-packages/perceval/backends/core/github.py", line 666, in fetch_items
    response = self.fetch(url_next, payload=payload)
  File "/usr/local/lib/python3.6/dist-packages/perceval/backends/core/github.py", line 650, in fetch
    response = super().fetch(url, payload, headers, method, stream, verify)
  File "/usr/local/lib/python3.6/dist-packages/perceval/client.py", line 131, in fetch
    response = self._fetch_from_remote(url, payload, headers, method, stream, verify)
  File "/usr/local/lib/python3.6/dist-packages/perceval/client.py", line 172, in _fetch_from_remote
    raise e
  File "/usr/local/lib/python3.6/dist-packages/perceval/client.py", line 167, in _fetch_from_remote
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://api.github.com/repos/kubernetes/kubernetes/issues?state=all&per_page=100&direction=asc&sort=updated&since=2014-01-01T00%3A00%3A00%2B00%3A00

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./bin/perceval", line 158, in <module>
    main()
  File "./bin/perceval", line 104, in main
    cmd.run()
  File "/usr/local/lib/python3.6/dist-packages/perceval/backend.py", line 393, in run
    raise RuntimeError(str(e))
RuntimeError: 502 Server Error: Bad Gateway for url: https://api.github.com/repos/kubernetes/kubernetes/issues?state=all&per_page=100&direction=asc&sort=updated&since=2014-01-01T00%3A00%3A00%2B00%3A00

real	0m14.001s
user	0m0.409s
sys	0m0.035s
```

I was initially thinking that this is due to the huge size of `k/k` repo but `torvalds/linux` is bigger and seems to work (never waited till finish, it would take hours! Interrupted after about 10 minutes): `time ./bin/perceval github torvalds linux --category issue -t "`cat /etc/github/oauth`" --sleep-for-rate --from-date 2014-01-01`

**Comment by lukaszgryglicki** [comment]
Seems like I know why `linux` works and `kubernetes` not. Kubernetes has 100s more issues and PRs (`linux` GitHub repo is only a mirror). Seems like `Perceval` is not able to process issues/PRs from repos with tens/hundreds of thousands of issues/PRs. probably some internal paging or something like this is needed, I don't think that user should call Perceval N times for `k/k` repo each time giving very short `date_from` - `date_to` ranged - this should be handled internally IMHO.

**Comment by lukaszgryglicki** [comment]
When I merged most recent `upstream/master` today it seems to work OK for `kubernetes/kubernetes` repo :)
That `upstream/master` merge works both when using single GitHub token and also with my new feature PR [adding support for GitHub tokens pool](https://github.com/chaoss/grimoirelab-perceval/pull/473).
I will give it more time...

**Comment by lukaszgryglicki** [comment]
Unfortunately, not that easy, now `too many 502 error messages` for command: `time ./bin/perceval github kubernetes kubernetes --category issue -t "`cat /etc/github/oauths`" --sleep-for-rate --from-date 2014-01-01`:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/root/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/root/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/root/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  [Previous line repeated 2 more times]
  File "/root/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 711, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/root/.local/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repositories/20580498/issues?state=all&per_page=100&direction=asc&sort=updated&since=2014-01-01T00%3A00%3A00%2B00%3A00&page=2&state=all&per_page=100&direction=asc&sort=updated&since=2014-01-01T00%3A00%3A00%2B00%3A00 (Caused by ResponseError('too many 502 error responses',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/perceval/backend.py", line 385, in run
    for item in items:
  File "/usr/local/lib/python3.6/dist-packages/perceval/backend.py", line 498, in fetch
    raise e
  File "/usr/local/lib/python3.6/dist-packages/perceval/backend.py", line 492, in fetch
    for item in items:
  File "/usr/local/lib/python3.6/dist-packages/perceval/backend.py", line 127, in fetch
    for item in self.fetch_items(category, **kwargs):
  File "/usr/local/lib/python3.6/dist-packages/perceval/backends/core/github.py", line 227, in __fetch_issues
    for raw_issues in issues_groups:
  File "/usr/local/lib/python3.6/dist-packages/perceval/backends/core/github.py", line 708, in fetch_items
    response = self.fetch(url_next, payload=payload)
  File "/usr/local/lib/python3.6/dist-packages/perceval/backends/core/github.py", line 672, in fetch
    response = super().fetch(url, payload, headers, method, stream, verify)
  File "/usr/local/lib/python3.6/dist-packages/perceval/client.py", line 131, in fetch
    response = self._fetch_from_remote(url, payload, headers, method, stream, verify)
  File "/usr/local/lib/python3.6/dist-packages/perceval/client.py", line 162, in _fetch_from_remote
    response = self.session.get(url, params=payload, headers=headers, stream=stream, verify=verify)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 520, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 630, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 499, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repositories/20580498/issues?state=all&per_page=100&direction=asc&sort=updated&since=2014-01-01T00%3A00%3A00%2B00%3A00&page=2&state=all&per_page=100&direction=asc&sort=updated&since=2014-01-01T00%3A00%3A00%2B00%3A00 (Caused by ResponseError('too many 502 error responses',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./bin/perceval", line 158, in <module>
    main()
  File "./bin/perceval", line 104, in main
    cmd.run()
  File "/usr/local/lib/python3.6/dist-packages/perceval/backend.py", line 393, in run
    raise RuntimeError(str(e))
RuntimeError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repositories/20580498/issues?state=all&per_page=100&direction=asc&sort=updated&since=2014-01-01T00%3A00%3A00%2B00%3A00&page=2&state=all&per_page=100&direction=asc&sort=updated&since=2014-01-01T00%3A00%3A00%2B00%3A00 (Caused by ResponseError('too many 502 error responses',))

real	2m9.951s
user	0m1.115s
sys	0m0.202s
2019-01-18 07:00:05 root@teststats:~/dev/grimoirelab-perceval# 
```

**Comment by lukaszgryglicki** [comment]
GitHub is unable to process all K8s issues at once. But I think `Perceval` should deal with that.
- First, detect that GitHub failed due to attempting to get too much data at once.
- Second: once detected retry dividing request into smaller parts (like for example iterate date ranges or divide by some other mean).
- Finally - when GitHub request divided into N smaller requests - run each of N requests in parallel.

I think Perceval should be more durable in such cases - it is sometimes used as a library - it should survive and deal with such problems. I can try to work on this is needed - but I don't know when I would have time for it.

**Comment by jgbarah** [comment]
@lukaszgryglicki thanks for your comments. I agree with you. i'm labeling this as "enhacement" and "help wanted", just in case somebody can help with this (in addition to you if you can find the time, of course).

**Comment by lukaszgryglicki** [comment]
Thanks!

**Comment by valeriocos** [comment]
It seems that kubernetes/kubernetes issue data can be fetched without problems. I tried a normal execution and an execution with the recent feature https://github.com/chaoss/grimoirelab-perceval/commit/637f280519539ee5afa54dfa6e7d8e07b316c99c, and the fetch process ended successfully.

@sduenas should we close this issue ?

**Comment by sduenas** [comment]
Yeah, let's close it. Feel free to reopen it if we find the same error again.

**Comment by lukaszgryglicki** [comment]
Great, thanks!
