### ISSUE TITLE
Error with `perceval git` on a new Ubuntu 18.04

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/grimoirelab-perceval#535]
I installed Ubuntu 18.04 fresh. 
Then followed the tutorial to install GrimoireLab (`v.0.2.23`) with Perceval (`v 0.12.16`) from pip3. 

Trying to use perceval using the following command:
```
perceval -g git https://github.com/chaoss/grimoirelab.git
```

I get the following error messages:
```
[2019-06-11 09:53:00,099 - root - INFO] - Sir Perceval is on his quest.
[2019-06-11 09:53:00,101 - perceval.backends.core.git - DEBUG] - Running command git clone --bare https://github.com/chaoss/grimoirelab.git /home/georg/.perceval/repositories/https://github.com/chaoss/grimoirelab.git-git (cwd: None, env: {'LANG': 'C', 'HOME': '/home/georg'})
Traceback (most recent call last):
  File "/home/georg/venvs/gl/lib/python3.6/site-packages/perceval/backends/core/git.py", line 1321, in _exec
    cwd=cwd, env=env)
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'git': 'git'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/georg/venvs/gl/lib/python3.6/site-packages/perceval/backend.py", line 472, in run
    for item in items:
  File "/home/georg/venvs/gl/lib/python3.6/site-packages/perceval/backend.py", line 589, in fetch
    raise e
  File "/home/georg/venvs/gl/lib/python3.6/site-packages/perceval/backend.py", line 583, in fetch
    for item in items:
  File "/home/georg/venvs/gl/lib/python3.6/site-packages/perceval/backend.py", line 162, in fetch
    for item in self.fetch_items(category, **kwargs):
  File "/home/georg/venvs/gl/lib/python3.6/site-packages/perceval/backends/core/git.py", line 155, in fetch_items
    latest_items, no_update)
  File "/home/georg/venvs/gl/lib/python3.6/site-packages/perceval/backends/core/git.py", line 268, in __fetch_from_repo
    repo = self.__create_git_repository()
  File "/home/georg/venvs/gl/lib/python3.6/site-packages/perceval/backends/core/git.py", line 319, in __create_git_repository
    repo = GitRepository.clone(self.uri, self.gitpath)
  File "/home/georg/venvs/gl/lib/python3.6/site-packages/perceval/backends/core/git.py", line 824, in clone
    cls._exec(cmd, env=env)
  File "/home/georg/venvs/gl/lib/python3.6/site-packages/perceval/backends/core/git.py", line 1324, in _exec
    raise RepositoryError(cause=str(e))
perceval.errors.RepositoryError: [Errno 2] No such file or directory: 'git': 'git'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/georg/venvs/gl/bin/perceval", line 158, in <module>
    main()
  File "/home/georg/venvs/gl/bin/perceval", line 104, in main
    cmd.run()
  File "/home/georg/venvs/gl/lib/python3.6/site-packages/perceval/backend.py", line 482, in run
    raise RuntimeError(str(e))
RuntimeError: [Errno 2] No such file or directory: 'git': 'git'

```

**Comment by GeorgLink** [comment]
the reason may be that I don't have git installed

**Comment by GeorgLink** [comment]
yes, now it works :/

Idea: include in the pip installation a check for all dependencies, including:
- git
- build-essential
