### ISSUE TITLE
[Question] trying to use groups backend

### ISSUE THREAD

**Issue by lukaszgryglicki** [chaoss/grimoirelab-perceval#538]
Hi, I'm trying to use `Groups.io` Perceval backend.
The documentation says that I need `GitHub OAuth token` but groups.io doesn't have an option to login via GitHub. I've created an account on groups.io and it can only allow logging in via standard email/password pair or via Google or via Facebook. I've checked all groups.io setting and there is no way to create API token there and their documentation says: `Authentication to the API is performed via HTTP Basic Auth, using a token received from the login API call` [here](https://groups.io/api#authentication-1). SO this is totally unclear what token should I provide.
Next group name, then documentation only says `perceval: error: the following arguments are required: group_name`, what is this group name? I want to get data from zephyr project, what should I pass there?
I've tried:
```
https://lists.zephyrproject.org/g/main/subgroups
https://lists.zephyrproject.org/g/main
https://lists.zephyrproject.org/g
https://lists.zephyrproject.org
lists.zephyrproject.org
zephyrproject
```
None works and the error message is always the same:
`perceval -g groupsio -t `cat /etc/github/oauth` lists.zephyrproject.org --mboxes-path zephyr_groupsio`:
```
[2019-06-18 08:01:44,323 - root - INFO] - Sir Perceval is on his quest.
[2019-06-18 08:01:44,326 - perceval.backends.core.groupsio - INFO] - Looking for messages from 'https://groups.io/g/lists.zephyrproject.org' since 1970-01-01 00:00:00+00:00
[2019-06-18 08:01:44,327 - perceval.backends.core.groupsio - INFO] - Downloading mboxes from 'https://groups.io/g/lists.zephyrproject.org'
[2019-06-18 08:01:44,327 - perceval.backends.core.groupsio - DEBUG] - Storing mboxes in 'zephyr_groupsio'
[2019-06-18 08:01:44,330 - urllib3.connectionpool - DEBUG] - Starting new HTTPS connection (1): api.groups.io
[2019-06-18 08:01:45,076 - urllib3.connectionpool - DEBUG] - https://api.groups.io:443 "GET /v1/downloadarchives?group_name=lists.zephyrproject.org HTTP/1.1" 400 58
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/perceval/backend.py", line 385, in run
    for item in items:
  File "/usr/local/lib/python3.6/dist-packages/perceval/backend.py", line 498, in fetch
    raise e
  File "/usr/local/lib/python3.6/dist-packages/perceval/backend.py", line 492, in fetch
    for item in items:
  File "/usr/local/lib/python3.6/dist-packages/perceval/backend.py", line 127, in fetch
    for item in self.fetch_items(category, **kwargs):
  File "/usr/local/lib/python3.6/dist-packages/perceval/backends/core/groupsio.py", line 101, in fetch_items
    mailing_list.fetch()
  File "/usr/local/lib/python3.6/dist-packages/perceval/backends/core/groupsio.py", line 170, in fetch
    success = self._download_archive(url, payload, auth, filepath)
  File "/usr/local/lib/python3.6/dist-packages/perceval/backends/core/groupsio.py", line 180, in _download_archive
    raise e
  File "/usr/local/lib/python3.6/dist-packages/perceval/backends/core/groupsio.py", line 177, in _download_archive
    r.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.groups.io/v1/downloadarchives?group_name=lists.zephyrproject.org

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/perceval", line 158, in <module>
    main()
  File "/usr/local/bin/perceval", line 104, in main
    cmd.run()
  File "/usr/local/lib/python3.6/dist-packages/perceval/backend.py", line 393, in run
    raise RuntimeError(str(e))
RuntimeError: 400 Client Error: Bad Request for url: https://api.groups.io/v1/downloadarchives?group_name=lists.zephyrproject.org
```

How can I use groupsio datasource, can you provide just one example call that works and instructions how to create this API token needed for example command to run?

I was following the main documentation and even the class methods description: https://buildmedia.readthedocs.org/media/pdf/perceval/latest/perceval.pdf

**Comment by sduenas** [comment]
**Groups.io** is full of tricks. I've been working with it recently and it was hard to understand how to run it. 

To get a token you need to run the next command:
```
curl "https://api.groups.io/v1/login" -u 123456: -d "email=<your email address>&password=<your password>"
```
The user must be `123456`.

Next, you have to subscribe your user to the mailing lists you want to track.

Once you have that, to analyze those mailing lists in `groups.io`  under a different domain, you have to use the name of the group plus the name of the subgroup. Something like the next should work:
```
perceval groupsio -t <your_token> "zephyrproject+main"
```

Let me know if this worked for you. I'll update the documentation if that's the case.

**Comment by lukaszgryglicki** [comment]
Thanks a lot. Will let you know soon.

**Comment by lukaszgryglicki** [comment]
So the first part (token related) works, I've created the following bash script to get token value and then call Perceval:
```
#!/bin/bash
if [ ! -f "/etc/groupsio/token" ]
then
  echo "No saved groups.io token"
  echo -n "groups.io email/login: "
  read email
  echo -n "groups.io password: "
  read -s pass
  echo ""
  response=`curl -s "https://api.groups.io/v1/login" -u 123456: -d "email=${email}&password=${pass}"`
  token=`echo $response | jq '.token'`
else
  token=`cat /etc/groupsio/token`
fi
if ( [ -z "$token" ] || [ "$token" = "null" ] )
then
  echo "Cannot get token value, exiting"
  exit 1
fi
if [ ! -f "/etc/groupsio/token" ]
then
  echo $token > /etc/groupsio/token
fi
echo "Token: $token"
perceval groupsio -t "$token" "zephyrproject+main"
```

- User is subscribed to the given list (zephyrproject).

But then using that token gives 400 error (just like before, 400 error means permission error):
```
Token: "(redacted)"
[2019-06-18 09:18:34,196] - Sir Perceval is on his quest.
[2019-06-18 09:18:34,198] - Looking for messages from 'https://groups.io/g/zephyrproject+main' since 1970-01-01 00:00:00+00:00
[2019-06-18 09:18:34,199] - Downloading mboxes from 'https://groups.io/g/zephyrproject+main'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/perceval/backend.py", line 385, in run
    for item in items:
  File "/usr/local/lib/python3.6/dist-packages/perceval/backend.py", line 498, in fetch
    raise e
  File "/usr/local/lib/python3.6/dist-packages/perceval/backend.py", line 492, in fetch
    for item in items:
  File "/usr/local/lib/python3.6/dist-packages/perceval/backend.py", line 127, in fetch
    for item in self.fetch_items(category, **kwargs):
  File "/usr/local/lib/python3.6/dist-packages/perceval/backends/core/groupsio.py", line 101, in fetch_items
    mailing_list.fetch()
  File "/usr/local/lib/python3.6/dist-packages/perceval/backends/core/groupsio.py", line 170, in fetch
    success = self._download_archive(url, payload, auth, filepath)
  File "/usr/local/lib/python3.6/dist-packages/perceval/backends/core/groupsio.py", line 180, in _download_archive
    raise e
  File "/usr/local/lib/python3.6/dist-packages/perceval/backends/core/groupsio.py", line 177, in _download_archive
    r.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.groups.io/v1/downloadarchives?group_name=zephyrproject%2Bmain

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/perceval", line 158, in <module>
    main()
  File "/usr/local/bin/perceval", line 104, in main
    cmd.run()
  File "/usr/local/lib/python3.6/dist-packages/perceval/backend.py", line 393, in run
    raise RuntimeError(str(e))
RuntimeError: 400 Client Error: Bad Request for url: https://api.groups.io/v1/downloadarchives?group_name=zephyrproject%2Bmain
```

**Comment by valeriocos** [comment]
@lukaszgryglicki , in case you want to know the group names your token is subscribed you can use this script: https://gist.github.com/valeriocos/676d90c58c56e2b17b882f2603283d39

Further info about how to get a token can be found also here:
https://beta.groups.io/g/api/topic/getting_a_auth_token/23025030?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,23025030

**Comment by valeriocos** [comment]
I successfully subscribe to zephyrproject main, the corresponding perceval command should be the following:
```
groupsio
zephyrproject
-t
....
 ```

**Comment by lukaszgryglicki** [comment]
Hi, I have "fdsfsdhsgfsdjh" in token value because it comes from `| jq '.token'` - my bad. I'll fix my script and retry - I've got this from your gist, thanks!

**Comment by lukaszgryglicki** [comment]
Works, thanks!

**Comment by valeriocos** [comment]
You are welcome @lukaszgryglicki . It sounds like a good idea to update docs with all these details.
