### ISSUE TITLE
[github] "Rate limit not initialized: 401 Client Error" when invoked from python script 

### ISSUE THREAD

**Issue by svysali** [chaoss/grimoirelab-perceval#546]
Hi,

I'm trying to fetch issues from a GitHub repository. I have perceval version 0.12.16. When I invoker perceval from the command line, I am able to fetch the issues.

However, when I try to get the issues through a python script, it fails. I downloaded [perceval_github_1.py](https://chaoss.github.io/grimoirelab-tutorial/perceval/scripts/perceval_github_1.py) and ran it and here's the error:

> Rate limit not initialized: 401 Client Error: Unauthorized for url: https://api.github.com/rate_limit
Rate limit not initialized: 401 Client Error: Unauthorized for url: https://api.github.com/rate_limit
Traceback (most recent call last):
  File "perceval_github_1.py", line 24, in <module>
    for item in repo.fetch():
  File "/miniconda3/lib/python3.7/site-packages/perceval/backend.py", line 160, in fetch
    self.client = self._init_client()
  File "/miniconda3/lib/python3.7/site-packages/perceval/backends/core/github.py", line 237, in _init_client
    self.archive, from_archive)
  File "/miniconda3/lib/python3.7/site-packages/perceval/backends/core/github.py", line 563, in __init__
    self._choose_best_api_token()
  File "/miniconda3/lib/python3.7/site-packages/perceval/backends/core/github.py", line 862, in _choose_best_api_token
    self._update_current_rate_limit()
  File "/miniconda3/lib/python3.7/site-packages/perceval/backends/core/github.py", line 907, in _update_current_rate_limit
    raise error
  File "/miniconda3/lib/python3.7/site-packages/perceval/backends/core/github.py", line 899, in _update_current_rate_limit
    response = super().fetch(url)
  File "/miniconda3/lib/python3.7/site-packages/perceval/client.py", line 132, in fetch
    response = self._fetch_from_remote(url, payload, headers, method, stream, verify)
  File "/miniconda3/lib/python3.7/site-packages/perceval/client.py", line 173, in _fetch_from_remote
    raise e
  File "/miniconda3/lib/python3.7/site-packages/perceval/client.py", line 168, in _fetch_from_remote
    response.raise_for_status()
  File "/miniconda3/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.github.com/rate_limit

Can you please let me know how this can be fixed?

Thanks,
Vysali.

**Comment by valeriocos** [comment]
Hi @svysali , thank you for using Perceval.

Please try to include the token in a list. One of the latest features added to the GitHub backend is the possiblity to pass a list of tokens, for instance:
``` 
backend = GitHub("chaoss", "grimoirelab-perceval", api_token=["token-1", "token-2"], archive=archive, sleep_for_rate=True)
```

Let us know if this solves your issue, otherwise please share your code.
Thanks!

**Comment by svysali** [comment]
Thank you @valeriocos. Once I changed the api_token to a list, I was able to retrieve the issues.
Thank you once again !

**Comment by valeriocos** [comment]
Great! thank you for the quick reply @svysali
