### ISSUE TITLE
failure extracting issues from openstack at launchpad

### ISSUE THREAD

**Issue by foundjem** [chaoss/grimoirelab-perceval#566]
I am trying to use Perceval to extract bug data from OpenStack at Launchpad, but every time I ran to this error: 

`Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/perceval/archive.py", line 181, in store
    payload_dump, headers_dump, data_dump))
sqlite3.IntegrityError: UNIQUE constraint failed: archive.hashcode

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/perceval/backend.py", line 472, in run
    for item in items:
  File "/usr/local/lib/python3.7/site-packages/perceval/backend.py", line 589, in fetch
    raise e
  File "/usr/local/lib/python3.7/site-packages/perceval/backend.py", line 583, in fetch
    for item in items:
  File "/usr/local/lib/python3.7/site-packages/perceval/backend.py", line 162, in fetch
    for item in self.fetch_items(category, **kwargs):
  File "/usr/local/lib/python3.7/site-packages/perceval/backends/core/launchpad.py", line 117, in fetch_items
    for issue in self._fetch_issues(from_date):
  File "/usr/local/lib/python3.7/site-packages/perceval/backends/core/launchpad.py", line 210, in _fetch_issues
    issue['bug_data'] = self.__fetch_issue_data(issue_id)
  File "/usr/local/lib/python3.7/site-packages/perceval/backends/core/launchpad.py", line 224, in __fetch_issue_data
    raw_issue = self.client.issue(issue_id)
  File "/usr/local/lib/python3.7/site-packages/perceval/backends/core/launchpad.py", line 343, in issue
    raw_text = self.__send_request(url_issue)
  File "/usr/local/lib/python3.7/site-packages/perceval/backends/core/launchpad.py", line 393, in __send_request
    r = self.fetch(url, payload=params)
  File "/usr/local/lib/python3.7/site-packages/perceval/client.py", line 132, in fetch
    response = self._fetch_from_remote(url, payload, headers, method, stream, verify)
  File "/usr/local/lib/python3.7/site-packages/perceval/client.py", line 177, in _fetch_from_remote
    self.archive.store(url, payload, headers, response)
  File "/usr/local/lib/python3.7/site-packages/perceval/archive.py", line 186, in store
    raise ArchiveError(cause=msg)
perceval.errors.ArchiveError: data storage error; cause: duplicated entry 92fb4f245d2204fe3b6968d10f9050bfc8786c84

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/perceval", line 158, in <module>
    main()
  File "/usr/local/bin/perceval", line 104, in main
    cmd.run()
  File "/usr/local/lib/python3.7/site-packages/perceval/backend.py", line 482, in run
    raise RuntimeError(str(e))
RuntimeError: data storage error; cause: duplicated entry 92fb4f245d2204fe3b6968d10f9050bfc8786c84`

Signed-off-by: Armstrong Foundjem <foundjem@ieee.org>

**Comment by valeriocos** [comment]
Hi @foundjem , thank you for using perceval. The error is due to a duplicated entry in the archive (a mechanism that stores the requests done to an API and the corresponding response into a relational database), please try to use the param `--no-archive`.

**Comment by valeriocos** [comment]
any news on this issue @foundjem ? thanks

**Comment by foundjem** [comment]
Hello @valeriocos, it seems working now.  Thanks for your help.

**Comment by valeriocos** [comment]
thank you for answering @foundjem , let's close this issue. Feel free to reopen it if needed
