### ISSUE TITLE
[meetup] The token is visible in the logs

### ISSUE THREAD

**Issue by jjmerchante** [chaoss/grimoirelab-perceval#567]
When you try to analyze a group that does not exist, an error is generated and the token that was being used is shown, for example for `events` group (does not exist):

`Error: Not Found for url: https://api.meetup.com/events/events?fields=event_hosts,featured,group_topics,plain_text_description,rsvpable,series&status=cancelled,upcoming,past,proposed,suggested&page=200&order=updated&access_token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxx&scroll=since%3A1970-01-01T00%3A00%3A00.000Z`

It would be better not to show it to prevent anyone reading the logs from obtaining private information.

**Comment by valeriocos** [comment]
Thank you @jjmerchante for reporting this issue, I'll have a look at it ASAP

**Comment by valeriocos** [comment]
The referenced PR should solve the problem. The output for a failing meetup group is now the following:
```
[2019-08-29 14:15:32,233] - Sir Perceval is on his quest.
[2019-08-29 14:15:32,235] - Fetching events of 'events' group from 2019-08-01 00:00:00+00:00 to --
Traceback (most recent call last):
  File "/home/slimbook/Escritorio/sources/perceval/perceval/backend.py", line 471, in run
    for item in items:
  File "/home/slimbook/Escritorio/sources/perceval/perceval/backend.py", line 588, in fetch
    raise e
  File "/home/slimbook/Escritorio/sources/perceval/perceval/backend.py", line 582, in fetch
    for item in items:
  File "/home/slimbook/Escritorio/sources/perceval/perceval/backend.py", line 161, in fetch
    for item in self.fetch_items(category, **kwargs):
  File "/home/slimbook/Escritorio/sources/perceval/perceval/backends/core/meetup.py", line 149, in fetch_items
    for evp in ev_pages:
  File "/home/slimbook/Escritorio/sources/perceval/perceval/backends/core/meetup.py", line 395, in events
    raise error
  File "/home/slimbook/Escritorio/sources/perceval/perceval/backends/core/meetup.py", line 388, in events
    for page in self._fetch(resource, params):
  File "/home/slimbook/Escritorio/sources/perceval/perceval/backends/core/meetup.py", line 466, in _fetch
    r = self.fetch(url, payload=params, headers=headers)
  File "/home/slimbook/Escritorio/sources/perceval/perceval/client.py", line 132, in fetch
    response = self._fetch_from_remote(url, payload, headers, method, stream, verify, auth)
  File "/home/slimbook/Escritorio/sources/perceval/perceval/client.py", line 173, in _fetch_from_remote
    raise e
  File "/home/slimbook/Escritorio/sources/perceval/perceval/client.py", line 168, in _fetch_from_remote
    response.raise_for_status()
  File "/home/slimbook/Escritorio/sources/venv/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.meetup.com/events/events?fields=event_hosts,featured,group_topics,plain_text_description,rsvpable,series&status=cancelled,upcoming,past,proposed,suggested&order=updated&scroll=since%3A2019-08-01T00%3A00%3A00.000Z&page=200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/slimbook/Escritorio/sources/perceval/bin/perceval", line 157, in <module>
    main()
  File "/home/slimbook/Escritorio/sources/perceval/bin/perceval", line 103, in main
    cmd.run()
  File "/home/slimbook/Escritorio/sources/perceval/perceval/backend.py", line 479, in run
    raise RuntimeError(str(e))
RuntimeError: 404 Client Error: Not Found for url: https://api.meetup.com/events/events?fields=event_hosts,featured,group_topics,plain_text_description,rsvpable,series&status=cancelled,upcoming,past,proposed,suggested&order=updated&scroll=since%3A2019-08-01T00%3A00%3A00.000Z&page=200
```
