### ISSUE TITLE
groupsio backend is not working

### ISSUE THREAD

**Issue by lukaszgryglicki** [chaoss/grimoirelab-perceval#586]
`perceval -g groupsio hyperledger -e "(redacted)" -p "(redacted)" --from-date 2019-10-01`:
```
[2019-11-10 14:41:39,460 - root - INFO] - Sir Perceval is on his quest.
[2019-11-10 14:41:39,462 - perceval.backends.core.groupsio - INFO] - Looking for messages from 'https://groups.io/g/hyperledger' since 2019-10-01 00:00:00+00:00
[2019-11-10 14:41:39,465 - urllib3.connectionpool - DEBUG] - Starting new HTTPS connection (1): groups.io:443
[2019-11-10 14:41:40,300 - urllib3.connectionpool - DEBUG] - https://groups.io:443 "POST /api/v1/login?email=[redacted]&password=KHJGKLHJGhjofFHKjhffhjkFkgj HTTP/1.1" 200 None
[2019-11-10 14:41:40,302 - perceval.backends.core.groupsio - DEBUG] - Groupsio email [redacted] authenticated in https://groups.io/api/v1
[2019-11-10 14:41:40,302 - perceval.backends.core.groupsio - INFO] - Downloading mboxes from 'https://groups.io/g/hyperledger'
[2019-11-10 14:41:40,303 - perceval.backends.core.groupsio - DEBUG] - Storing mboxes in '/root/.perceval/mailinglists/https://groups.io/g/hyperledger'
[2019-11-10 14:41:40,303 - perceval.backends.core.groupsio - DEBUG] - Get groupsio paginated subscriptions from https://groups.io/api/v1/getsubs
[2019-11-10 14:41:40,501 - urllib3.connectionpool - DEBUG] - https://groups.io:443 "GET /api/v1/getsubs?limit=100 HTTP/1.1" 200 None
[2019-11-10 14:41:40,749 - urllib3.connectionpool - DEBUG] - https://groups.io:443 "GET /api/v1/downloadarchives?group_id=16341 HTTP/1.1" 400 62
Traceback (most recent call last):
  File "/repos/grimoirelab-perceval/perceval/backend.py", line 601, in run
    for item in big.items:
  File "/repos/grimoirelab-perceval/perceval/backend.py", line 777, in __fetch
    raise e
  File "/repos/grimoirelab-perceval/perceval/backend.py", line 771, in __fetch
    for item in items:
  File "/repos/grimoirelab-perceval/perceval/backend.py", line 215, in fetch
    for item in self.fetch_items(category, **kwargs):
  File "/repos/grimoirelab-perceval/perceval/backends/core/groupsio.py", line 128, in fetch_items
    mailing_list.fetch()
  File "/repos/grimoirelab-perceval/perceval/backends/core/groupsio.py", line 205, in fetch
    success = self._download_archive(url, payload, filepath)
  File "/repos/grimoirelab-perceval/perceval/backends/core/groupsio.py", line 242, in _download_archive
    raise e
  File "/repos/grimoirelab-perceval/perceval/backends/core/groupsio.py", line 239, in _download_archive
    r.raise_for_status()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://groups.io/api/v1/downloadarchives?group_id=16341

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/perceval", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/repos/grimoirelab-perceval/bin/perceval", line 157, in <module>
    main()
  File "/repos/grimoirelab-perceval/bin/perceval", line 103, in main
    cmd.run()
  File "/repos/grimoirelab-perceval/perceval/backend.py", line 611, in run
    raise RuntimeError(str(e))
RuntimeError: 400 Client Error: Bad Request for url: https://groups.io/api/v1/downloadarchives?group_id=16341
```
Credentials are correct, check on the groups.io site and I can login with them. Group exists, if I change group name other error is returned.

Can anybody show me a working `perceval groupsio` example?

**Comment by valeriocos** [comment]
@lukaszgryglicki, I guess the group doesn't have enabled the permission to download archives. We experienced the same issue with another group, the solution was to ask the group's owner to enable that permission. More details at:
- https://beta.groups.io/g/api/topic/enable_download_archives/34544765?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,34544765
- https://groups.io/g/GroupManagersForum/topic/39414187#21350

To be sure that the error is on the group's configuration, I executed the command `perceval groupsio hyperledger -e valcos@bitergia.com -p xxxx` and got the same error as you. By inspecting the response returned at: https://github.com/chaoss/grimoirelab-perceval/blob/master/perceval/backends/core/groupsio.py#L237, I see this value:
`b'{"object":"error","type":"inadequate_permissions","extra":""}\n'`. This error is coherent with the initial guess and with what reported at: https://groups.io/api#download-archives.

The same perceval command works fine for another group, for instance `perceval groupsio OPNFV -e valcos@bitergia.com -p xxxx`

Hope this helps, please close this issue if the answer above solves your problem, thanks!

**Comment by lukaszgryglicki** [comment]
OK thanks for the info, that wasn't obvious from the error returned.

**Comment by valeriocos** [comment]
you are right! maybe a log message would help. Thanks for the feedback

**Comment by lukaszgryglicki** [comment]
There is no `OPNFV` group (at least Perceval says that):
```
2019-11-11 08:21:55,663 [Groupsio] Incremental from: 2019-10-01 00:00:00+00:00 for https://groups.io/g/OPNFV
2019-11-11 08:21:55,663 Looking for messages from 'https://groups.io/g/OPNFV' since 2019-10-01 00:00:00
2019-11-11 08:21:55,876 Downloading mboxes from 'https://groups.io/g/OPNFV'
2019-11-11 08:21:55,953 Error feeding raw from groupsio (https://groups.io/g/OPNFV): Group id not found for group name OPNFV
Traceback (most recent call last):
  File "/repos/grimoirelab-elk/grimoire_elk/elk.py", line 228, in feed_backend
    ocean_backend.feed(**params)
  File "/repos/grimoirelab-elk/grimoire_elk/raw/elastic.py", line 230, in feed
    self.feed_items(items)
  File "/repos/grimoirelab-elk/grimoire_elk/raw/elastic.py", line 246, in feed_items
    for item in items:
  File "/repos/grimoirelab-perceval/perceval/backend.py", line 215, in fetch
    for item in self.fetch_items(category, **kwargs):
  File "/repos/grimoirelab-perceval/perceval/backends/core/groupsio.py", line 128, in fetch_items
    mailing_list.fetch()
  File "/repos/grimoirelab-perceval/perceval/backends/core/groupsio.py", line 200, in fetch
    group_id = self.__find_group_id()
  File "/repos/grimoirelab-perceval/perceval/backends/core/groupsio.py", line 267, in __find_group_id
    raise BackendError(cause=msg)
perceval.errors.BackendError: Group id not found for group name OPNFV
2019-11-11 08:21:55,954 [groupsio] Done collection for https://groups.io/g/OPNFV
2019-11-11 08:21:55,955 Backend feed completed
2019-11-11 08:21:56,027 Total identities loaded 0 
2019-11-11 08:21:56,032 Total items enriched 0 
2019-11-11 08:21:56,032 [groupsio] Done enrichment for https://groups.io/g/OPNFV
2019-11-11 08:21:56,032 Enrich backend completed
2019-11-11 08:21:56,032 Finished in 0.01 min
```

**Comment by valeriocos** [comment]
Are you registered to https://lists.opnfv.org/g/main? If you don't join the group, you cannot download the archives (AFAIK).

**Comment by lukaszgryglicki** [comment]
Just added a user to this group, will see if that helps, thanks.

**Comment by lukaszgryglicki** [comment]
So for `edgexfoundry` with correct email/password pair (because otherwise, the error is different):
```
2019-11-14 13:03:37,637 [Groupsio] Incremental from: None for https://groups.io/g/edgexfoundry
2019-11-14 13:03:37,637 Looking for messages from 'https://groups.io/g/edgexfoundry' since 1970-01-01 00:00:00+00:00
2019-11-14 13:03:37,955 Downloading mboxes from 'https://groups.io/g/edgexfoundry'
2019-11-14 13:03:38,141 Error feeding raw from groupsio (https://groups.io/g/edgexfoundry): 400 Client Error: Bad Request for url: https://groups.io/api/v1/downloadarchives?group_id=15155
Traceback (most recent call last):
  File "/repos/grimoirelab-elk/grimoire_elk/elk.py", line 228, in feed_backend
    ocean_backend.feed(**params)
  File "/repos/grimoirelab-elk/grimoire_elk/raw/elastic.py", line 230, in feed
    self.feed_items(items)
  File "/repos/grimoirelab-elk/grimoire_elk/raw/elastic.py", line 246, in feed_items
    for item in items:
  File "/repos/grimoirelab-perceval/perceval/backend.py", line 215, in fetch
    for item in self.fetch_items(category, **kwargs):
  File "/repos/grimoirelab-perceval/perceval/backends/core/groupsio.py", line 128, in fetch_items
    mailing_list.fetch()
  File "/repos/grimoirelab-perceval/perceval/backends/core/groupsio.py", line 205, in fetch
    success = self._download_archive(url, payload, filepath)
  File "/repos/grimoirelab-perceval/perceval/backends/core/groupsio.py", line 242, in _download_archive
    raise e
  File "/repos/grimoirelab-perceval/perceval/backends/core/groupsio.py", line 239, in _download_archive
    r.raise_for_status()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://groups.io/api/v1/downloadarchives?group_id=15155
2019-11-14 13:03:38,142 [groupsio] Done collection for https://groups.io/g/edgexfoundry
2019-11-14 13:03:38,143 Backend feed completed
2019-11-14 13:03:38,197 Total identities loaded 0 
2019-11-14 13:03:38,202 Total items enriched 0 
2019-11-14 13:03:38,202 [groupsio] Done enrichment for https://groups.io/g/edgexfoundry
2019-11-14 13:03:38,202 Enrich backend completed
2019-11-14 13:03:38,202 Finished in 0.01 min
```
Same for `hyperledger`:
```
2019-11-14 13:05:39,336 Error feeding raw from groupsio (https://groups.io/g/hyperledger): 400 Client Error: Bad Request for url: https://groups.io/api/v1/downloadarchives?group_id=16341
Traceback (most recent call last):
  File "/repos/grimoirelab-elk/grimoire_elk/elk.py", line 228, in feed_backend
    ocean_backend.feed(**params)
  File "/repos/grimoirelab-elk/grimoire_elk/raw/elastic.py", line 230, in feed
    self.feed_items(items)
  File "/repos/grimoirelab-elk/grimoire_elk/raw/elastic.py", line 246, in feed_items
    for item in items:
  File "/repos/grimoirelab-perceval/perceval/backend.py", line 215, in fetch
    for item in self.fetch_items(category, **kwargs):
  File "/repos/grimoirelab-perceval/perceval/backends/core/groupsio.py", line 128, in fetch_items
    mailing_list.fetch()
  File "/repos/grimoirelab-perceval/perceval/backends/core/groupsio.py", line 205, in fetch
    success = self._download_archive(url, payload, filepath)
  File "/repos/grimoirelab-perceval/perceval/backends/core/groupsio.py", line 242, in _download_archive
    raise e
  File "/repos/grimoirelab-perceval/perceval/backends/core/groupsio.py", line 239, in _download_archive
    r.raise_for_status()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://groups.io/api/v1/downloadarchives?group_id=16341
2019-11-14 13:05:39,338 [groupsio] Done collection for https://groups.io/g/hyperledger
2019-11-14 13:05:39,339 Backend feed completed
2019-11-14 13:05:39,396 Total identities loaded 0 
2019-11-14 13:05:39,401 Total items enriched 0 
2019-11-14 13:05:39,402 [groupsio] Done enrichment for https://groups.io/g/hyperledger
2019-11-14 13:05:39,402 Enrich backend completed
2019-11-14 13:05:39,402 Finished in 0.01 min
```

If I put wrong goup name or wrong credentials error is different:
```
2019-11-14 13:06:15,519 [Groupsio] Incremental from: None for https://groups.io/g/hyperledger
2019-11-14 13:06:15,519 Looking for messages from 'https://groups.io/g/hyperledger' since 1970-01-01 00:00:00+00:00
2019-11-14 13:06:15,781 Downloading mboxes from 'https://groups.io/g/hyperledger'
2019-11-14 13:06:15,857 Error feeding raw from groupsio (https://groups.io/g/hyperledger): Group id not found for group name hyperledger
Traceback (most recent call last):
  File "/repos/grimoirelab-elk/grimoire_elk/elk.py", line 228, in feed_backend
    ocean_backend.feed(**params)
  File "/repos/grimoirelab-elk/grimoire_elk/raw/elastic.py", line 230, in feed
    self.feed_items(items)
  File "/repos/grimoirelab-elk/grimoire_elk/raw/elastic.py", line 246, in feed_items
    for item in items:
  File "/repos/grimoirelab-perceval/perceval/backend.py", line 215, in fetch
    for item in self.fetch_items(category, **kwargs):
  File "/repos/grimoirelab-perceval/perceval/backends/core/groupsio.py", line 128, in fetch_items
    mailing_list.fetch()
  File "/repos/grimoirelab-perceval/perceval/backends/core/groupsio.py", line 200, in fetch
    group_id = self.__find_group_id()
  File "/repos/grimoirelab-perceval/perceval/backends/core/groupsio.py", line 267, in __find_group_id
    raise BackendError(cause=msg)
perceval.errors.BackendError: Group id not found for group name hyperledger
2019-11-14 13:06:15,859 [groupsio] Done collection for https://groups.io/g/hyperledger
2019-11-14 13:06:15,860 Backend feed completed
2019-11-14 13:06:15,922 Total identities loaded 0 
2019-11-14 13:06:15,927 Total items enriched 0 
2019-11-14 13:06:15,927 [groupsio] Done enrichment for https://groups.io/g/hyperledger
2019-11-14 13:06:15,928 Enrich backend completed
2019-11-14 13:06:15,928 Finished in 0.01 min
```

For both groups I've subscribed to groups and received email confirming that I'm subscribed.

Any ideas (or is it just disabled downloading archives)?

**Comment by valeriocos** [comment]
I guess it's due to disabled downloading of archives. For `hyperledger`, the permission of the group are:
```
    "group_name": "hyperledger", <-------
    "id": 6024902,
    ...
    "perms": {
        "archives_visible": true,
        "ban_members": false,
        "calendar_visible": true,
        "can_post": false,
        "can_vote": true,
        "chat_visible": false,
        "database_visible": false,
        "delete_group": false,
        "download_archives": false, <---------------
        "download_entire_group": false,
        "download_members": false,
        "edit_archives": false,
        ...
    },
```

**Comment by lukaszgryglicki** [comment]
Ok, so we can close this unless there is a way to do that anyway, but I guess if API disallows this there is nothing you can do, right?

**Comment by valeriocos** [comment]
Yes, you should ask the admin groups to enable it (https://groups.io/g/GroupManagersForum/topic/39414187#21350)
