### ISSUE TITLE
GitHub data source error: NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by lukaszgryglicki** [chaoss/grimoirelab-perceval#590]
GitHub data source error:
```
2019-11-14 09:22:36,882 Error feeding raw from github (https://github.com/hyperledger/sawtooth-core): 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/repos/grimoirelab-elk/grimoire_elk/elk.py", line 228, in feed_backend
    ocean_backend.feed(**params)
  File "/repos/grimoirelab-elk/grimoire_elk/raw/elastic.py", line 230, in feed
    self.feed_items(items)
  File "/repos/grimoirelab-elk/grimoire_elk/raw/elastic.py", line 246, in feed_items
    for item in items:
  File "/repos/grimoirelab-perceval/perceval/backend.py", line 215, in fetch
    for item in self.fetch_items(category, **kwargs):
  File "/repos/grimoirelab-perceval/perceval/backends/core/github.py", line 344, in __fetch_pull_requests
    pull[field + '_data'] = self.__get_pull_requested_reviewers(pull['number'])
  File "/repos/grimoirelab-perceval/perceval/backends/core/github.py", line 444, in __get_pull_requested_reviewers
    user_data = self.__get_user(requested_reviewer['login'])
```

**Comment by valeriocos** [comment]
The error is with this pull request: https://github.com/hyperledger/sawtooth-core/pull/93.
The last requested reviewer (right side) is `None`, you can see in the UI only a yellow circle (without name)

**Comment by valeriocos** [comment]
I'm preparing the fix, thanks @lukaszgryglicki for reporting this issue.

**Comment by lukaszgryglicki** [comment]
Thanks! There will be more probably, I'm running Perceval on 3152 endpoints...

**Comment by lukaszgryglicki** [comment]
Hi, so quick question - should I just built new `grimoire` images from corresponding master branches and I will have the fixed version?
