### ISSUE TITLE
jira perceval error - is this due to permission denied?

### ISSUE THREAD

**Issue by lukaszgryglicki** [chaoss/grimoirelab-perceval#592]
Is this due to permission denied? If so can we have a better error message, becaus enow whatever I change I'm getting the same error and I can't find why it fails even with `-g` flag turned on:
`perceval -g jira https://jira.hyperledger.org --project BUR -u (redacted) -p (redacted) --no-archive --verify False`:
```
[2019-11-14 10:21:10,245 - root - INFO] - Sir Perceval is on his quest.
[2019-11-14 10:21:10,247 - perceval.backends.core.jira - INFO] - Looking for issues at site 'https://jira.hyperledger.org', in project 'BUR' and updated from '1970-01-01 00:00:00+00:00'
[2019-11-14 10:21:10,248 - urllib3.connectionpool - DEBUG] - Starting new HTTPS connection (1): jira.hyperledger.org:443
[2019-11-14 10:21:20,561 - urllib3.connectionpool - DEBUG] - https://jira.hyperledger.org:443 "GET /rest/api/2/field HTTP/1.1" 401 None
Traceback (most recent call last):
  File "/repos/grimoirelab-perceval/perceval/backend.py", line 601, in run
    for item in big.items:
  File "/repos/grimoirelab-perceval/perceval/backend.py", line 777, in __fetch
    raise e
  File "/repos/grimoirelab-perceval/perceval/backend.py", line 771, in __fetch
    for item in items:
  File "/repos/grimoirelab-perceval/perceval/backend.py", line 215, in fetch
    for item in self.fetch_items(category, **kwargs):
  File "/repos/grimoirelab-perceval/perceval/backends/core/jira.py", line 161, in fetch_items
    fields = json.loads(self.client.get_fields())
  File "/repos/grimoirelab-perceval/perceval/backends/core/jira.py", line 354, in get_fields
    req = self.fetch(url)
  File "/repos/grimoirelab-perceval/perceval/client.py", line 132, in fetch
    response = self._fetch_from_remote(url, payload, headers, method, stream, verify, auth)
  File "/repos/grimoirelab-perceval/perceval/client.py", line 173, in _fetch_from_remote
    raise e
  File "/repos/grimoirelab-perceval/perceval/client.py", line 168, in _fetch_from_remote
    response.raise_for_status()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error:  for url: https://jira.hyperledger.org/rest/api/2/field

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/perceval", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/repos/grimoirelab-perceval/bin/perceval", line 157, in <module>
    main()
  File "/repos/grimoirelab-perceval/bin/perceval", line 103, in main
    cmd.run()
  File "/repos/grimoirelab-perceval/perceval/backend.py", line 611, in run
    raise RuntimeError(str(e))
RuntimeError: 401 Client Error:  for url: https://jira.hyperledger.org/rest/api/2/field
```

**Comment by valeriocos** [comment]
Hi @lukaszgryglicki , yes it seems to. However, it is a bit strange because I have tried without credentials and it works: `jira https://jira.hyperledger.org --project BUR`.

**Comment by lukaszgryglicki** [comment]
OK, thanks for an info.

**Comment by valeriocos** [comment]
you're welcome! It may be better to keep this issue open to investigate this behavior.

**Comment by valeriocos** [comment]
@lukaszgryglicki I'm not able to replicate the issue, I tried with the following commands and all of them worked.
- perceval jira -u ... -p ... https://jira.hyperledger.org --project BUR
- perceval jira https://jira.hyperledger.org --project BUR
- perceval jira -u ... -p ...  jira https://jira.hyperledger.org
- perceval jira https://jira.hyperledger.org

let's close this issue, feel free to reopen it if needed, thanks!
