### ISSUE TITLE
Perceval gerrit backend - KeyError

### ISSUE THREAD

**Issue by lukaszgryglicki** [chaoss/grimoirelab-perceval#593]
SSH priv key is put in `/root/.ssh/id_rsa`, public kay is added to gerrit:
`p2o.py --enrich --index (redacted) --index-enrich (redacted) -e (redacted) --db-host mariadb.mariadb --db-sortinghat sortinghat --db-user sortinghat --db-password (redacted) gerrit gerrit.hyperledger.org --user (redacted) --disable-host-key-check --no-archive`:
```
2019-11-14 10:35:16,308 [Gerrit] Incremental from: 2019-11-12 19:48:22+00:00 for gerrit.hyperledger.org
2019-11-14 10:35:25,249 Received 500 reviews in 8.76s
2019-11-14 10:35:25,515 [gerrit] Done collection for gerrit.hyperledger.org
2019-11-14 10:35:25,516 Backend feed completed
2019-11-14 10:35:25,927 Adding the identities to SortingHat
2019-11-14 10:35:26,266 Total identities added to SH: 101
2019-11-14 10:35:26,600 Adding the identities to SortingHat
2019-11-14 10:35:26,974 Total identities added to SH: 101
2019-11-14 10:35:27,309 Adding the identities to SortingHat
2019-11-14 10:35:27,655 Total identities added to SH: 101
2019-11-14 10:35:28,018 Adding the identities to SortingHat
2019-11-14 10:35:28,382 Total identities added to SH: 101
2019-11-14 10:35:28,922 Error enriching ocean from gerrit (gerrit.hyperledger.org): 'reviewer'
Traceback (most recent call last):
  File "/repos/grimoirelab-elk/grimoire_elk/elk.py", line 657, in enrich_backend
    total_ids = load_identities(ocean_backend, enrich_backend)
  File "/repos/grimoirelab-elk/grimoire_elk/elk.py", line 415, in load_identities
    for identity in identities:
  File "/repos/grimoirelab-elk/grimoire_elk/enriched/gerrit.py", line 160, in get_identities
    user = comment['reviewer']
KeyError: 'reviewer'
2019-11-14 10:35:28,927 [gerrit] Done enrichment for gerrit.hyperledger.org
2019-11-14 10:35:28,928 Enrich backend completed
2019-11-14 10:35:28,928 Finished in 0.21 min
```

**Comment by lukaszgryglicki** [comment]
```
2019-11-14 12:25:20,705 Total identities added to SH: 101
2019-11-14 12:25:21,114 Error enriching ocean from gerrit (gerrit.hyperledger.org): 'reviewer'
Traceback (most recent call last):
  File "/repos/grimoirelab-elk/grimoire_elk/elk.py", line 657, in enrich_backend
    total_ids = load_identities(ocean_backend, enrich_backend)
  File "/repos/grimoirelab-elk/grimoire_elk/elk.py", line 415, in load_identities
    for identity in identities:
  File "/repos/grimoirelab-elk/grimoire_elk/enriched/gerrit.py", line 160, in get_identities
    user = comment['reviewer']
KeyError: 'reviewer'
2019-11-14 12:25:21,119 [gerrit] Done enrichment for gerrit.hyperledger.org
2019-11-14 12:25:21,120 Enrich backend completed
2019-11-14 12:25:21,120 Finished in 0.19 min
: 2019-11-14 12:25:10,010 [Gerrit] Incremental from: 2019-11-14 12:01:17+00:00 for gerrit.hyperledger.org
2019-11-14 12:25:17,495 Received 500 reviews in 7.31s
2019-11-14 12:25:17,511 [gerrit] Done collection for gerrit.hyperledger.org
2019-11-14 12:25:17,511 Backend feed completed
2019-11-14 12:25:18,075 Adding the identities to SortingHat
2019-11-14 12:25:18,456 Total identities added to SH: 101
2019-11-14 12:25:18,726 Adding the identities to SortingHat
2019-11-14 12:25:19,135 Total identities added to SH: 101
2019-11-14 12:25:19,550 Adding the identities to SortingHat
2019-11-14 12:25:19,955 Total identities added to SH: 101
2019-11-14 12:25:20,236 Adding the identities to SortingHat
2019-11-14 12:25:20,705 Total identities added to SH: 101
2019-11-14 12:25:21,114 Error enriching ocean from gerrit (gerrit.hyperledger.org): 'reviewer'
Traceback (most recent call last):
  File "/repos/grimoirelab-elk/grimoire_elk/elk.py", line 657, in enrich_backend
    total_ids = load_identities(ocean_backend, enrich_backend)
  File "/repos/grimoirelab-elk/grimoire_elk/elk.py", line 415, in load_identities
    for identity in identities:
  File "/repos/grimoirelab-elk/grimoire_elk/enriched/gerrit.py", line 160, in get_identities
    user = comment['reviewer']
KeyError: 'reviewer'
```
