### ISSUE TITLE
[phabricator] You must use withSourcePHIDs() to query edges. (code: ERR-CONDUIT-CORE)

### ISSUE THREAD

**Issue by valeriocos** [chaoss/grimoirelab-perceval#605]
```
You must use withSourcePHIDs() to query edges. (code: ERR-CONDUIT-CORE)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/elk.py", line 228, in feed_backend
    ocean_backend.feed(**params)
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/raw/elastic.py", line 234, in feed
    self.feed_items(items)
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/raw/elastic.py", line 250, in feed_items
    for item in items:
  File "/usr/local/lib/python3.5/dist-packages/perceval/backend.py", line 215, in fetch
    for item in self.fetch_items(category, **kwargs):
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/phabricator.py", line 112, in fetch_items
    for task in self.__fetch_tasks(from_date):
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/phabricator.py", line 242, in __fetch_tasks
    tasks_trans = self.__fetch_and_parse_tasks_transactions(*tasks_ids)
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/phabricator.py", line 331, in __fetch_and_parse_tasks_transactions
    tt['oldValue_data'] = self.__resolve_project_ids(tt['oldValue'])
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/phabricator.py", line 388, in __resolve_project_ids
    obj = self.__resolve_project_ids_from_list(obj)
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/phabricator.py", line 409, in __resolve_project_ids_from_list
    project_info = self.__get_or_fetch_project(e)
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/phabricator.py", line 294, in __get_or_fetch_project
    phids = self.__fetch_and_parse_phids(project_id)
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/phabricator.py", line 422, in __fetch_and_parse_phids
    raw_phids = self.client.phids(*phids)
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/phabricator.py", line 552, in phids
    response = self._call(self.PHAB_PHIDS, params)
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/phabricator.py", line 604, in _call
    code=result['error_code'])
perceval.backends.core.phabricator.ConduitError: You must use withSourcePHIDs() to query edges. (code: ERR-CONDUIT-CORE)
```

**Comment by valeriocos** [comment]
I wasn't able to reproduce the issue found in the logs. 
It seems that it can be due to inconsistent data stored in two different SQL tables (https://secure.phabricator.com/T10705), thus the problem has been probably fixed in upstream.
