### ISSUE TITLE
[gitlab] Getting 404 client errors; incorrect URL encoding?

### ISSUE THREAD

**Issue by svdo** [chaoss/grimoirelab-perceval#606]
I have configured a gitlab repo in my projects json, like this:

```json
{
  "my-project": {
    "meta": {
      "title": "my-project"
    },
    "git": [
      "https://user:token@gitlab.my-enterprise.com/my-project/my-repo.git"
    ],
    "gitlab:issue": [
      "https://user:token@gitlab.my-enterprise.com/my-project/my-repo.git"
    ],
    "gitlab:merge": [
      "https://user:token@gitlab.my-enterprise.com/my-project/my-repo.git"
    ],
    "colic": [
      "https://user:token@gitlab.my-enterprise.com/my-project/my-repo.git"
    ],
    "cocom": [
      "https://user:token@gitlab.my-enterprise.com/my-project/my-repo.git"
    ]
  }
}
```

When I run Grimoirelab (0.2.36, built myself as full-3p including third-party tools), I get errors about issues and merge requests. The error looks like this:

```
2020-01-10 15:35:43,145 - grimoire_elk.elk - ERROR - Error feeding raw from gitlab (https://gitlab.my-enterprise.com/my-project/my-repo.git): 404 Client Error: Not Found for url: https://gitlab.my-enterprise.com/api/v4/projects/my-project%2Fmy-repo.git/issues?updated_after=1970-01-01T00%3A00%3A00%2B00%3A00&sort=asc&per_page=100&order_by=updated_at&state=all
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/elk.py", line 228, in feed_backend
    ocean_backend.feed(**params)
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/raw/elastic.py", line 230, in feed
    self.feed_items(items)
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/raw/elastic.py", line 246, in feed_items
    for item in items:
  File "/usr/local/lib/python3.5/dist-packages/perceval/backend.py", line 215, in fetch
    for item in self.fetch_items(category, **kwargs):
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/gitlab.py", line 259, in __fetch_issues
    for raw_issues in issues_groups:
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/gitlab.py", line 644, in fetch_items
    response = self.fetch(url_next, payload=payload)
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/gitlab.py", line 628, in fetch
    response = super().fetch(url, payload, headers, method, stream)
  File "/usr/local/lib/python3.5/dist-packages/perceval/client.py", line 132, in fetch
    response = self._fetch_from_remote(url, payload, headers, method, stream, verify, auth)
  File "/usr/local/lib/python3.5/dist-packages/perceval/client.py", line 173, in _fetch_from_remote
    raise e
  File "/usr/local/lib/python3.5/dist-packages/perceval/client.py", line 168, in _fetch_from_remote
    response.raise_for_status()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://gitlab.my-enterprise.com/api/v4/projects/my-project%2Fmy-repo.git/issues?updated_after=1970-01-01T00%3A00%3A00%2B00%3A00&sort=asc&per_page=100&order_by=updated_at&state=all
```

What strikes me as potentially incorrect, is that the URL in the error message contains both slashes ('/') and escaped slashes ('%2F'). I'm aware of the need to type '%2F' in my projects json when there are more directories, but my understanding was that in this case the way I typed it should be correct. Is this a bug or am I doing something wrong? Thanks!!

**Comment by valeriocos** [comment]
Hi @svdo,

I guess the error is due to wrong URLs in the projects.json. For instance, taking as a reference the call at: `https://gitlab.my-enterprise.com/api/v4/projects/my-project%2Fmy-repo.git/issues?updated_after=1970-01-01T00%3A00%3A00%2B00%3A00&sort=asc&per_page=100&order_by=updated_at&state=all`, it fails since there is no project `my-project%2Fmy-repo.git` (the one available via the API is my-project%2Fmy-repo).

Please, try to remove the `.git`. from your projects.json
```
{
  "my-project": {
    "meta": {
      "title": "my-project"
    },
    "git": [
      "https://user:token@gitlab.my-enterprise.com/my-project/my-repo"
    ],
    "gitlab:issue": [
      "https://user:token@gitlab.my-enterprise.com/my-project/my-repo"
    ],
    "gitlab:merge": [
      "https://user:token@gitlab.my-enterprise.com/my-project/my-repo"
    ],
    "colic": [
      "https://user:token@gitlab.my-enterprise.com/my-project/my-repo"
    ],
    "cocom": [
      "https://user:token@gitlab.my-enterprise.com/my-project/my-repo"
    ]
  }
}
```

WRT '%2F' there shouldn't be any problem. The URL defined in the projects.json is passed to perceval, which creates the correct endpoint for first-level projects (e.g., https://github.com/chaoss/grimoirelab-perceval/blob/master/perceval/backends/core/gitlab.py#L644). In case of error, the exception is propagated to ELK, which prints the repo URL where the fail occurred (without '%2F').

Note that in case your gitlab project is nested, the URL should be:
`https://gitlab.com/gitlab-org/my-project%2my-sub-project`

**Comment by svdo** [comment]
Thanks for your assistance, @valeriocos. Unfortunately this does _not_ solve the error, it is still the same. For completeness, this is the one about the merge requests:

```
2020-01-11 10:21:02,430 - grimoire_elk.elk - ERROR - Error feeding raw from gitlab (https://gitlab.my-enterprise.com/my-project/my-repo): 404 Client Error: Not Found for url: https://gitlab.my-enterprise.com/api/v4/projects/my-project%2Fmy-repo/merge_requests?per_page=100&view=simple&updated_after=1970-01-01T00%3A00%3A00%2B00%3A00&state=all&order_by=updated_at&sort=asc
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/elk.py", line 228, in feed_backend
    ocean_backend.feed(**params)
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/raw/elastic.py", line 230, in feed
    self.feed_items(items)
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/raw/elastic.py", line 246, in feed_items
    for item in items:
  File "/usr/local/lib/python3.5/dist-packages/perceval/backend.py", line 215, in fetch
    for item in self.fetch_items(category, **kwargs):
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/gitlab.py", line 303, in __fetch_merge_requests
    for mr_item in self.__fetch_merge_requests_data(fetch_from_date):
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/gitlab.py", line 316, in __fetch_merge_requests_data
    for raw_merges in merges_groups:
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/gitlab.py", line 644, in fetch_items
    response = self.fetch(url_next, payload=payload)
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/gitlab.py", line 628, in fetch
    response = super().fetch(url, payload, headers, method, stream)
  File "/usr/local/lib/python3.5/dist-packages/perceval/client.py", line 132, in fetch
    response = self._fetch_from_remote(url, payload, headers, method, stream, verify, auth)
  File "/usr/local/lib/python3.5/dist-packages/perceval/client.py", line 173, in _fetch_from_remote
    raise e
  File "/usr/local/lib/python3.5/dist-packages/perceval/client.py", line 168, in _fetch_from_remote
    response.raise_for_status()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://gitlab.my-enterprise.com/api/v4/projects/my-project%2Fmy-repo/merge_requests?per_page=100&view=simple&updated_after=1970-01-01T00%3A00%3A00%2B00%3A00&state=all&order_by=updated_at&sort=asc
Collection for gitlab:merge: finished after 00:00:00 hours
```

**Comment by valeriocos** [comment]
You're welcome @svdo, can you share the dashboard.cfg/setup.cfg and the credentials.cfg?

**Comment by svdo** [comment]
This is my [credentials.cfg](https://github.com/chaoss/grimoirelab-perceval/files/4049694/credentials.cfg.txt). Besides the `projects.json` shown above I don't have anything else. I'm running it like this:

```bash
docker run -p 5601:5601 -p 9000:9200 \
    -v $(pwd)/logs:/logs \
    -v $(pwd)/projects.json:/projects.json \
    -v $(pwd)/credentials.cfg:/override.cfg \
    -v $(pwd)/es-data:/var/lib/elasticsearch \
    -t grimoirelab/full-3p
```

**Comment by valeriocos** [comment]
Your credentials.cfg looks OK (I generally put only the tokens there, while the other section info are in the dashboard.cfg), it only misses the token attributes.

```
...
[gitlab:issue]
raw_index = gitlab_issues-raw
enriched_index = gitlab_issues
no-archive = true
enterprise-url = https://gitlab.my-enterprise.com
sleep-for-rate = true
api-token = <YOUR-API-TOKEN> <---

[gitlab:merge]
raw_index = gitlab_merge_requests-raw
enriched_index = gitlab_merge_requests
no-archive = true
enterprise-url = https://gitlab.my-enterprise.com
category = merge_request
sleep-for-rate = true
api-token = <YOUR-API-TOKEN> <---
```

Can you try the following projects.json?
```
{
  "my-project": {
    "meta": {
      "title": "my-project"
    },
    "git": [
      "https://user:token@gitlab.my-enterprise.com/my-project/my-repo"
    ],
    "gitlab:issue": [
      "https://gitlab.my-enterprise.com/my-project/my-repo"
    ],
    "gitlab:merge": [
      "https://gitlab.my-enterprise.com/my-project/my-repo"
    ],
    "colic": [
      "https://user:token@gitlab.my-enterprise.com/my-project/my-repo"
    ],
    "cocom": [
      "https://user:token@gitlab.my-enterprise.com/my-project/my-repo"
    ]
  }
}
```

**Comment by svdo** [comment]
Right, including the api tokens does the trick. So that means that the tokens have to be BOTH in credentials.cfg and projects.json?

**Comment by valeriocos** [comment]
Just for git or graal backends (the latter inherit from the git backend), since this is the way of cloning a private repo. In the other cases, it shouldn't be needed.
