### ISSUE TITLE
[twitter] backend usage with docker grimoirelab/full

### ISSUE THREAD

**Issue by ioiobzit** [chaoss/grimoirelab-perceval#608]
Hello,

I've made a test installation with docker and so far so good. The ```git``` and ```github``` backends are working.
Now I tried to add data from Twitter.

I've created the Twitter bearer token using [this script](https://gist.github.com/valeriocos/7d4d28f72f53fbce49f1512ba77ef5f6) edited the credentials.cfg and added the twitter token like so. _please note that the access_token has a % symbol_

```
[github]
api-token = [redacted]
[twitter]
token_type = bearer
access_token  = [redacted]
```
and the projects.json
```
[...]
        ],
        "twitter": [
        "MYTWITTERHANDLE"
        ]
[...]
```

As soon as I start the docker-compose file this error appears:
```
grimoire       | Starting SirMordred to build a GrimoireLab dashboard
grimoire       | This will usually take a while...
grimoire       | Traceback (most recent call last):
grimoire       |   File "/usr/local/bin/sirmordred", line 125, in <module>
grimoire       |     config = Config(args.config_files[0], args.config_files[1:])
grimoire       |   File "/usr/local/lib/python3.5/dist-packages/sirmordred/config.py", line 62, in __init__
grimoire       |     self.__read_conf_files()
grimoire       |   File "/usr/local/lib/python3.5/dist-packages/sirmordred/config.py", line 733, in __read_conf_files
grimoire       |     raw_conf = {s: dict(parser.items(s)) for s in parser.sections()}
grimoire       |   File "/usr/local/lib/python3.5/dist-packages/sirmordred/config.py", line 733, in <dictcomp>
grimoire       |     raw_conf = {s: dict(parser.items(s)) for s in parser.sections()}
grimoire       |   File "/usr/lib/python3.5/configparser.py", line 855, in items
grimoire       |     return [(option, value_getter(option)) for option in d.keys()]
grimoire       |   File "/usr/lib/python3.5/configparser.py", line 855, in <listcomp>
grimoire       |     return [(option, value_getter(option)) for option in d.keys()]
grimoire       |   File "/usr/lib/python3.5/configparser.py", line 852, in <lambda>
grimoire       |     section, option, d[option], d)
grimoire       |   File "/usr/lib/python3.5/configparser.py", line 393, in before_get
grimoire       |     self._interpolate_some(parser, option, L, value, section, defaults, 1)
grimoire       |   File "/usr/lib/python3.5/configparser.py", line 443, in _interpolate_some
grimoire       |     "found: %r" % (rest,))
grimoire       | configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%[THIS PART AFTER THE % HAS BEEN REDACTED AS IT IS PART OF THE access_token IN credentials.cfg]"'
grimoire       | Failed to start SirMordred: 1

```
I tried to put the twitter access token under single and double quotes without success.

What else can I try?
Thank you.

**Comment by valeriocos** [comment]
Please try %%. I couldn't test it, but if I remember correctly it should work.

Let me know how it goes

**Comment by ioiobzit** [comment]
That worked.

The next error were:

```
Starting SirMordred to build a GrimoireLab dashboard
This will usually take a while...
Error while consuming configuration:  ('Missing section param:', 'twitter', 'raw_index')
Failed to start SirMordred: 1
Starting container: grimoire
Starting Elasticsearch
Starting Elasticsearch Server:.
Waiting for Elasticsearch to start...
tcp        0      0 0.0.0.0:9200            0.0.0.0:*               LISTEN      -                   
Elasticsearch started
Starting MariaDB
Starting MariaDB database server: mysqld ..
Waiting for MariaDB to start...
tcp6       0      0 :::3306                 :::*                    LISTEN      -                   
MariaDB started
Starting Kibiter
Waiting for Kibiter to start...
..Kibiter started
Starting SirMordred to build a GrimoireLab dashboard
This will usually take a while...
Error while consuming configuration:  ('Missing section param:', 'twitter', 'enriched_index')
```

This is how I set the **credentials.cfg** to make it work:

```
[github]
api-token = [redacted]
raw_index = github_raw
enriched_index = github_enriched

[twitter]
api-token  = [redacted]%%[redacted]
raw_index = twitter_raw
enriched_index = twitter_enriched
```

Thank you.
