### ISSUE TITLE
No way to set API Username for Discourse

### ISSUE THREAD

**Issue by mbbroberg** [chaoss/grimoirelab-perceval#626]
Hey gang, I run a private Discourse instance and I'm unable to run perceval successfully against it. 

```bash
$ perceval discourse 'https://discourse.opensource.com' -t $DISCOURSE_API_TOKEN --from-date '2019-08-01'
[2020-03-10 10:39:06,284] - Sir Perceval is on his quest.
[2020-03-10 10:39:06,295] - Looking for topics at 'https://discourse.opensource.com', updated from '2019-08-01 00:00:00+00:00'
Traceback (most recent call last):
  File "/Users/mbbroberg/.pyenv/versions/3.7.3/lib/python3.7/site-packages/perceval/backend.py", line 601, in run
    for item in big.items:
  File "/Users/mbbroberg/.pyenv/versions/3.7.3/lib/python3.7/site-packages/perceval/backend.py", line 777, in __fetch
    raise e
  File "/Users/mbbroberg/.pyenv/versions/3.7.3/lib/python3.7/site-packages/perceval/backend.py", line 771, in __fetch
    for item in items:
  File "/Users/mbbroberg/.pyenv/versions/3.7.3/lib/python3.7/site-packages/perceval/backend.py", line 215, in fetch
    for item in self.fetch_items(category, **kwargs):
  File "/Users/mbbroberg/.pyenv/versions/3.7.3/lib/python3.7/site-packages/perceval/backends/core/discourse.py", line 117, in fetch_items
    topics_ids = self.__fetch_and_parse_topics_ids(from_date)
  File "/Users/mbbroberg/.pyenv/versions/3.7.3/lib/python3.7/site-packages/perceval/backends/core/discourse.py", line 191, in __fetch_and_parse_topics_ids
    response = self.client.topics_page(page)
  File "/Users/mbbroberg/.pyenv/versions/3.7.3/lib/python3.7/site-packages/perceval/backends/core/discourse.py", line 328, in topics_page
    params=params)
  File "/Users/mbbroberg/.pyenv/versions/3.7.3/lib/python3.7/site-packages/perceval/backends/core/discourse.py", line 395, in _call
    r = self.fetch(url, payload=params)
  File "/Users/mbbroberg/.pyenv/versions/3.7.3/lib/python3.7/site-packages/perceval/client.py", line 132, in fetch
    response = self._fetch_from_remote(url, payload, headers, method, stream, verify, auth)
  File "/Users/mbbroberg/.pyenv/versions/3.7.3/lib/python3.7/site-packages/perceval/client.py", line 173, in _fetch_from_remote
    raise e
  File "/Users/mbbroberg/.pyenv/versions/3.7.3/lib/python3.7/site-packages/perceval/client.py", line 168, in _fetch_from_remote
    response.raise_for_status()
  File "/Users/mbbroberg/.pyenv/versions/3.7.3/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://discourse.opensource.com/latest.json?api_key=TOKEN9&page=0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mbbroberg/.pyenv/versions/3.7.3/bin/perceval", line 157, in <module>
    main()
  File "/Users/mbbroberg/.pyenv/versions/3.7.3/bin/perceval", line 103, in main
    cmd.run()
  File "/Users/mbbroberg/.pyenv/versions/3.7.3/lib/python3.7/site-packages/perceval/backend.py", line 611, in run
    raise RuntimeError(str(e))
RuntimeError: 403 Client Error: Forbidden for url: https://discourse.opensource.com/latest.json?api_key=TOKEN9&page=0
```
(Note: I forgot to delete my token when first uploading so I've reset them in Discourse 🤦‍♂)

I confirmed that Discourse requires a username to accompany the API token: 

```
curl -X GET "https://discourse.opensource.com/admin/users/list/active.json" \
-H "Api-Key: <MY TOKEN>" \
-H "Api-Username: < MY USERNAME >"
```
☝️ Works perfectly. 

I took a [look at `discourse.py`](https://github.com/chaoss/grimoirelab-perceval/blob/master/perceval/backends/core/discourse.py#L325) and see it's configured to accept a username, but there's no command-line flag to get me there. 

Where is that configured exactly? I'd be happy to open a PR to add it. Thanks!

**Comment by valeriocos** [comment]
Hi @mbbroberg ,

Maybe I'm missing something. The command line param is here: https://github.com/chaoss/grimoirelab-perceval/blob/master/perceval/backends/core/discourse.py#L428 ?

Have you tried the following?
```
perceval discourse 'https://discourse.opensource.com' -t $DISCOURSE_API_TOKEN --api-username ... --from-date '2019-08-01'
```

**Comment by mbbroberg** [comment]
Hey @valeriocos, that param isn't recognized from the cli: 

```bash
$ perceval discourse 'https://discourse.opensource.com' -t $DISCOURSE_API_TOKEN --api-username mbbroberg --from-date '2019-08-01'
[2020-03-13 08:09:27,836] - Sir Perceval is on his quest.
usage: perceval [-h] [--category CATEGORY] [--tag TAG] [--filter-classified]
                [--from-date FROM_DATE] [-t API_TOKEN]
                [--archive-path ARCHIVE_PATH] [--no-archive] [--fetch-archive]
                [--archived-since ARCHIVED_SINCE] [-o OUTFILE] [--json-line]
                [--max-retries MAX_RETRIES] [--sleep-time SLEEP_TIME]
                url
perceval: error: unrecognized arguments: --api-username mbbroberg
```

**Comment by valeriocos** [comment]
Interesting, I'll try to have a look at it asap.

**Comment by mbbroberg** [comment]
@valeriocos nothing urgent on my end - enjoy your weekend 😄

**Comment by Syn3rman** [comment]
Hey @mbbroberg,
I tried setting up the dev environment for Perceval, which appeared to work (it accepted the cli argument but gave me a forbidden error because I had set a bogus api token). However, the same command when run outside the venv gave me the error that you are facing. Thus, I downloaded the source code for the [current release for perceval](https://github.com/chaoss/grimoirelab-perceval/releases), and found that the cli arguments are missing, as you can see here:

![Screenshot from 2020-03-14 16-55-56](https://user-images.githubusercontent.com/31011197/76681169-fb055b00-6615-11ea-9655-2c3860357ccd.png)


I guess the issue will be fixed in the next release, but [valerio](https://github.com/valeriocos) can confirm if this was the case.

Cheers,
Aditya!

**Comment by valeriocos** [comment]
sorry for the late reply @Syn3rman ! Thanks for helping with this issue! Yes, the issue will be fixed as soon as the pypi version is updated. In the meanwhile, your solution is a great workaround! Could you write the steps to help @mbbroberg run perceval on his discourse using the master branch (e.g, create/activate a virtual env, clone the repo, install perceval using the requirements.txt, ...)?

**Comment by Syn3rman** [comment]
Sure @valeriocos!

Hey @mbbroberg,
If you decide to go this way, you can use the following commands to set up a dev env to run perceval:

1. Clone the repo locally using:
```
git clone https://github.com/chaoss/grimoirelab-perceval.git
```

2. Navigate into the directory:
```
cd grimoirelab-perceval/
```
3. Create and activate a virtual environment:
```
virtualenv dev_env
source dev_env/bin/activate
```

4. Install requirements: 
```
pip3 install -r requirements.txt
pip3 install .
```

5. Now you can use perceval using: 
```
perceval discourse 'https://discourse.opensource.com' -t $DISCOURSE_API_TOKEN --api-username mbbroberg --from-date '2019-08-01
```
and you'll be good to go :tada:

**Comment by valeriocos** [comment]
thanks @Syn3rman

**Comment by mbbroberg** [comment]
Wow, very kind of yoou @Syn3rman and @valeriocos. Thank you both 🥇

**Comment by valeriocos** [comment]
You're welcome @mbbroberg . If the solution at https://github.com/chaoss/grimoirelab-perceval/issues/626#issuecomment-599088032 solves your problem, please close this issue.

Thanks!

**Comment by mbbroberg** [comment]
Great - confirmed it's fixed as of https://github.com/chaoss/grimoirelab-perceval/commit/745b467e1f82cdd25bf438dc6f4b7cfeb2feef5b.
