### ISSUE TITLE
[gerrit] sortKey error when enriching gerrit data

### ISSUE THREAD

**Issue by code-sleuth** [chaoss/grimoirelab-perceval#633]
Command:
```
p2o.py --enrich --index lfn-odl-gerrit-raw --index-enrich lfn-odl-gerrit -e [redacted] -g --scroll-size 1000 --db-host [redacted] --db-[redacted] [redacted] --db-user [redacted] --db-password [redacted] gerrit git.opendaylight.org --user [redacted]
```

Error:
```
2020-03-11 19:29:47,255 GETTING MORE REVIEWS 500 >= 500
2020-03-11 19:29:47,255 Error feeding raw from gerrit (git.opendaylight.org): 'sortKey'
Traceback (most recent call last):
  File "/repos/grimoirelab-elk/grimoire_elk/elk.py", line 228, in feed_backend
    ocean_backend.feed(**params)
  File "/repos/grimoirelab-elk/grimoire_elk/raw/elastic.py", line 234, in feed
    self.feed_items(items)
  File "/repos/grimoirelab-elk/grimoire_elk/raw/elastic.py", line 250, in feed_items
    for item in items:
  File "/repos/grimoirelab-perceval/perceval/backend.py", line 221, in fetch
    for item in self.fetch_items(category, **kwargs):
  File "/repos/grimoirelab-perceval/perceval/backends/core/gerrit.py", line 121, in fetch_items
    for review in fetcher:
  File "/repos/grimoirelab-perceval/perceval/backends/core/gerrit.py", line 266, in _fetch_gerrit
    last_item = self.client.next_retrieve_group_item(last_item, review)
  File "/repos/grimoirelab-perceval/perceval/backends/core/gerrit.py", line 390, in next_retrieve_group_item
    next_item = entry['sortKey']
KeyError: 'sortKey'
```

**Comment by valeriocos** [comment]
Hi @code-sleuth, thank you for reporting this issue and @lukaszgryglicki for having a look at it.

The `sortKey` param has been deprecated in gerrit 2.9 (https://stackoverflow.com/questions/24606079/gerrit-rest-api-cannot-use-sortkey-to-resume-a-query) in favor of the `--start` param (https://gerrit-review.googlesource.com/Documentation/cmd-query.html#_options). The latter is already supported by the Gerrit backend, however it was applied only for gerrit > 2.9.x (https://github.com/chaoss/grimoirelab-perceval/blob/master/perceval/backends/core/gerrit.py#L489).

The following fix should solve the error:
```
index 71d2acd..9149eb1 100644
--- a/perceval/backends/core/gerrit.py
+++ b/perceval/backends/core/gerrit.py
@@ -380,7 +380,7 @@ class GerritClient():
 
         gerrit_version = self.version
 
-        if gerrit_version[0] == 2 and gerrit_version[1] > 9:
+        if (gerrit_version[0] == 2 and gerrit_version[1] > 9) or gerrit_version[0] == 3:
             if last_item is None:
                 next_item = 0
             else:
@@ -486,7 +486,7 @@ class GerritClient():
         gerrit_version = self.version
 
         if last_item is not None:
-            if gerrit_version[0] == 2 and gerrit_version[1] >= 9:
+            if (gerrit_version[0] == 2 and gerrit_version[1] >= 9) or gerrit_version[0] == 3:
                 cmd += " --start=" + str(last_item)
             else:
                 cmd += " resume_sortkey:" + last_item
```

**Comment by lukaszgryglicki** [comment]
Will it be merged into master?

**Comment by valeriocos** [comment]
Yes @lukaszgryglicki , probably between today or tomorrow. I'm checking the tests to see if they should be updated.

- Do you want to submit the fix?
- Do you have time to check the fix on your instances?

Thanks

**Comment by lukaszgryglicki** [comment]
I can create a PR tomorrow.

**Comment by valeriocos** [comment]
Let's speed up things, I'm going to submit a PR. It would be great if you can check it on your instances.

**Comment by lukaszgryglicki** [comment]
OK will do.

**Comment by valeriocos** [comment]
Thanks @lukaszgryglicki !

**Comment by lukaszgryglicki** [comment]
Confirmed that this fix [works](https://github.com/chaoss/grimoirelab-perceval/pull/634#issuecomment-603053391).
