### ISSUE TITLE
[groupsio] perceval returns 400 Client Error with correct credentials and permissions

### ISSUE THREAD

**Issue by teragopher** [chaoss/grimoirelab-perceval#650]
Operating System: **macOS Catalina (10.15.3)**
Perceval version:  **0.12.24**

Issue:  Running this command to fetch data from the group
```
perceval groupsio 'onap+onap-discuss' -e [redacted]  -p [redacted] --from-date '2020-01-25'
```

and i get this error: 

```
[2020-04-09 13:45:50,349] - Sir Perceval is on his quest.
[2020-04-09 13:45:50,350] - Looking for messages from 'https://groups.io/g/onap+onap-discuss' since 2020-01-25 00:00:00+00:00
[2020-04-09 13:45:52,953] - Downloading mboxes from 'https://groups.io/g/onap+onap-discuss'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/perceval/backend.py", line 601, in run
    for item in big.items:
  File "/usr/local/lib/python3.7/site-packages/perceval/backend.py", line 777, in __fetch
    raise e
  File "/usr/local/lib/python3.7/site-packages/perceval/backend.py", line 771, in __fetch
    for item in items:
  File "/usr/local/lib/python3.7/site-packages/perceval/backend.py", line 215, in fetch
    for item in self.fetch_items(category, **kwargs):
  File "/usr/local/lib/python3.7/site-packages/perceval/backends/core/groupsio.py", line 128, in fetch_items
    mailing_list.fetch()
  File "/usr/local/lib/python3.7/site-packages/perceval/backends/core/groupsio.py", line 205, in fetch
    success = self._download_archive(url, payload, filepath)
  File "/usr/local/lib/python3.7/site-packages/perceval/backends/core/groupsio.py", line 242, in _download_archive
    raise e
  File "/usr/local/lib/python3.7/site-packages/perceval/backends/core/groupsio.py", line 239, in _download_archive
    r.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://groups.io/api/v1/downloadarchives?group_id=19846

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/perceval", line 157, in <module>
    main()
  File "/usr/local/bin/perceval", line 103, in main
    cmd.run()
  File "/usr/local/lib/python3.7/site-packages/perceval/backend.py", line 611, in run
    raise RuntimeError(str(e))
RuntimeError: 400 Client Error: Bad Request for url: https://groups.io/api/v1/downloadarchives?group_id=19846
```

However querying the groupsio api directly works, I get the data

command:
```
curl "https://groups.io/api/v1/downloadarchives?group_id=19846&start_time=2020-01-25T00:00:00Z" -b "cookies.curl" --output onap-discuss.zip
```

**Comment by valeriocos** [comment]
Hi @teragopher , thank you for using Perceval!

It seems you are using an old version of Perceval, for instance the line `File "/usr/local/lib/python3.7/site-packages/perceval/backends/core/groupsio.py", line 242, in _download_archive` doesn't match with the current version of the backend: https://github.com/chaoss/grimoirelab-perceval/blob/master/perceval/backends/core/groupsio.py#L242.

Can you install perceval from source code and try again?

Thanks!

**Comment by teragopher** [comment]
@valeriocos Thanks a bunch .... works now

**Comment by valeriocos** [comment]
You're welcome @teragopher !
