### ISSUE TITLE
Perceval git backend error "item['data']['Author']"

### ISSUE THREAD

**Issue by lukaszgryglicki** [chaoss/grimoirelab-perceval#651]
```
2020-04-10 19:11:27,931 Error enriching raw from git (https://github.com/cloudfoundry/bosh-aws-cpi-release): 'Author'
Traceback (most recent call last):
  File "/repos/grimoirelab-elk/grimoire_elk/elk.py", line 525, in enrich_backend
    total_ids = load_identities(ocean_backend, enrich_backend)
  File "/repos/grimoirelab-elk/grimoire_elk/elk.py", line 285, in load_identities
    for identity in identities:
  File "/repos/grimoirelab-elk/grimoire_elk/enriched/git.py", line 139, in get_identities
    if item['data']['Author']:
KeyError: 'Author'
```

**Comment by valeriocos** [comment]
Hi @lukaszgryglicki, I'm trasferring this issue to ELK
