### ISSUE TITLE
RepositoryError: git command - fatal: could not create leading directories of 'C:\Users\I523597/.perceval/repositories/https://github.com/shikha0208/metrics.git-git'

### ISSUE THREAD

**Issue by shikha0208** [chaoss/grimoirelab-perceval#656]
Unable to run the basic perceval command.

**python perceval git https://github.com/shikha0208/metrics.git**

Error is   
**File "C:\Perceval\grimoirelab-perceval-master\perceval\backends\core\git.py", line 1338, in _exec
    raise RepositoryError(cause=cause)
perceval.errors.RepositoryError: git command - fatal: could not create leading directories of 'C:\Users\I523597/.perceval/repositories/https://github.com/shikha0208/metrics.git-git'**

Whole command run description
 python perceval git https://github.com/shikha0208/metrics.git                                                                                                                                [2020-04-29 01:23:27,072] - Sir Perceval is on his quest.
Traceback (most recent call last):
  File "C:\Perceval\grimoirelab-perceval-master\perceval\backend.py", line 618, in run
    for item in big.items:
  File "C:\Perceval\grimoirelab-perceval-master\perceval\backend.py", line 794, in __fetch
    raise e
  File "C:\Perceval\grimoirelab-perceval-master\perceval\backend.py", line 788, in __fetch
    for item in items:
  File "C:\Perceval\grimoirelab-perceval-master\perceval\backend.py", line 226, in fetch
    for item in self.fetch_items(category, **kwargs):
  File "C:\Perceval\grimoirelab-perceval-master\perceval\backends\core\git.py", line 160, in fetch_items
    commits = self.__fetch_from_repo(from_date, to_date, branches,
  File "C:\Perceval\grimoirelab-perceval-master\perceval\backends\core\git.py", line 274, in __fetch_from_repo
    repo = self.__create_git_repository()
  File "C:\Perceval\grimoirelab-perceval-master\perceval\backends\core\git.py", line 325, in __create_git_repository
    repo = GitRepository.clone(self.uri, self.gitpath)
  File "C:\Perceval\grimoirelab-perceval-master\perceval\backends\core\git.py", line 833, in clone
    cls._exec(cmd, env=env)
  File "C:\Perceval\grimoirelab-perceval-master\perceval\backends\core\git.py", line 1338, in _exec
    raise RepositoryError(cause=cause)
perceval.errors.RepositoryError: git command - fatal: could not create leading directories of 'C:\Users\I523597/.perceval/repositories/https://github.com/shikha0208/metrics.git-git'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "perceval", line 168, in <module>
    main()
  File "perceval", line 114, in main
    cmd.run()
  File "C:\Perceval\grimoirelab-perceval-master\perceval\backend.py", line 630, in run
    raise RuntimeError(str(e))
RuntimeError: git command - fatal: could not create leading directories of 'C:\Users\I523597/.perceval/repositories/https://github.com/shikha0208/metrics.git-git'

**Kindly let me know the  #issue,**
@valeriocos and others

**Comment by valeriocos** [comment]
Hi @shikha0208 , thank you for your interest in using Perceval!

The problem is that the Git backend doesn't work on Windows. There are similar issues already reported on the issue tracker:
- https://github.com/chaoss/grimoirelab-perceval/issues/654
- https://github.com/chaoss/grimoirelab-perceval/issues/447
- https://github.com/chaoss/grimoirelab-perceval/pull/526
- https://github.com/chaoss/grimoirelab-perceval/issues/399

Possible workarounds are:
- Download [virtualbox](https://www.virtualbox.org/wiki/Downloads), install a Linux distribution (e.g., Ubuntu) and then install Perceval in it
- Explore the solution proposed at https://github.com/chaoss/grimoirelab-perceval/issues/399
- Explore the containerized version of Perceval: https://github.com/chaoss/grimoirelab-perceval/tree/master/docker/images
- Follow the getting started at https://github.com/chaoss/grimoirelab#using-docker-compose, once you have the containers running, enter in the mordred one and execute perceval
     - `docker exec -it <hash-container-mordred> bash`
     - `perceval --help`

**Comment by sduenas** [comment]
@shikha0208 try to use it with the parameter `--git-path` active. Set there the directory where you want to store the repo to analyze. That should fix that problem. In any case, I think it will fail after that for other reasons.

Keep us posted.

**Comment by shikha0208** [comment]
Yes it works.Thank you
