### ISSUE TITLE
[googlehits] Returns None object

### ISSUE THREAD

**Issue by vchrombie** [chaoss/grimoirelab-perceval#668]
Here is the command which I have executed
```
$ perceval googlehits "bitergia grimoirelab"
```

The log of the execution :point_down: 
```
/home/p0tt3r/chaoss/sources/VENV_DIR/bin/python /home/p0tt3r/chaoss/sources/grimoirelab-perceval/bin/perceval googlehits "bitergia grimoirelab"
[2020-05-17 19:25:37,706] - Sir Perceval is on his quest.
[2020-05-17 19:25:37,989] - Fetching data for '['bitergia grimoirelab']'
[2020-05-17 19:25:37,990] - Fetching hits for 'bitergia grimoirelab'
Traceback (most recent call last):
  File "/home/p0tt3r/chaoss/sources/grimoirelab-perceval/perceval/backend.py", line 618, in run
    for item in big.items:
  File "/home/p0tt3r/chaoss/sources/grimoirelab-perceval/perceval/backend.py", line 794, in __fetch
    raise e
  File "/home/p0tt3r/chaoss/sources/grimoirelab-perceval/perceval/backend.py", line 788, in __fetch
    for item in items:
  File "/home/p0tt3r/chaoss/sources/grimoirelab-perceval/perceval/backend.py", line 226, in fetch
    for item in self.fetch_items(category, **kwargs):
  File "/home/p0tt3r/chaoss/sources/grimoirelab-perceval/perceval/backends/core/googlehits.py", line 111, in fetch_items
    hits = self.__parse_hits(hits_raw)
  File "/home/p0tt3r/chaoss/sources/grimoirelab-perceval/perceval/backends/core/googlehits.py", line 173, in __parse_hits
    hit_string = bs_result.find("div", id="resultStats").text
AttributeError: 'NoneType' object has no attribute 'text'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/p0tt3r/chaoss/sources/grimoirelab-perceval/bin/perceval", line 168, in <module>
    main()
  File "/home/p0tt3r/chaoss/sources/grimoirelab-perceval/bin/perceval", line 114, in main
    cmd.run()
  File "/home/p0tt3r/chaoss/sources/grimoirelab-perceval/perceval/backend.py", line 630, in run
    raise RuntimeError(str(e))
RuntimeError: 'NoneType' object has no attribute 'text'

Process finished with exit code 1
```

**Comment by vchrombie** [comment]
I am looking for what might have gone wrong. 
I think the `id` or something might have changed which caused the error, not sure tho. I will check it once.

```
    hit_string = bs_result.find("div", id="resultStats").text
```

**Comment by valeriocos** [comment]
Hi @vchrombie , you're right something has changed upstream.

The div `resultStats` isn't returned when running Perceval. If you perform the search in your browser and inspect the html, you should find a div with id `"result-stats"`. It contains the number of hits for the given search.

**Comment by vchrombie** [comment]
> The div `resultStats` isn't returned when running Perceval. If you perform the search in your browser and inspect the html, you should find a div with id `"result-stats"`. It contains the number of hits for the given search.

Yes, @valeriocos. I understood the error. I checked the google search too in the browser and `result-stats` is the required id. I tried replacing the id
```
    hit_string = bs_result.find("div", id="resultStats").text
```
and checked the bs_result in [googlehits.py#L172](https://github.com/chaoss/grimoirelab-perceval/blob/master/perceval/backends/core/googlehits.py#L172), but didn't find any id `result-stats`. I couldn't find the number too. :thinking: 

I have created a gist with the dump, [bs_result](https://gist.github.com/vchrombie/04f3368b7e8f18ded6a1395284818fb3#file-bs_result).

**Comment by valeriocos** [comment]
If I understand correctly the `result-stats` div is now added dynamically by some Javascript code, however BeautifulSoup doesn't deal with this dynamic part. Thus, the value of `result-stats` doesn't show up at https://github.com/chaoss/grimoirelab-perceval/blob/master/perceval/backends/core/googlehits.py#L172, but it is visible when inspecting (or viewing the source code of) the page in the browser.

Can you check if BeautifulSoup has some options to deal with the dynamic content? Otherwise we should evaluate other options to retrieve the dynamic content (some pointers below):
- https://stackoverflow.com/questions/17597424/how-to-retrieve-the-values-of-dynamic-html-content-using-python
- https://stackoverflow.com/questions/15866426/beautifulsoup-not-grabbing-dynamic-content
- https://realpython.com/headless-selenium-testing-with-python-and-phantomjs/

**Comment by vchrombie** [comment]
> https://github.com/chaoss/grimoirelab-perceval/issues/668#issuecomment-630084276

Hi @valeriocos 
I have checked the pointers which you have shared and also searched for it a bit more.

I have some conclusions regarding it.
1. AFAIK, we cannot use requests, in this case, it is suitable only for static content.
2. We can use selenium for this, but it has its own pros (it works, the only thing) and cons (it is slow and takes up a lot of memory).

Reference: https://kiwidamien.github.io/webscraping-beyond-beautifulsoup-and-selenium.html

Selenium uses a browser, it means almost like browsing using python and I feel it makes the things complicated which might not suit for perceval.

@sduenas, do you have any comments?

**Comment by sduenas** [comment]
If Google has changed how results are retrieved when we run a query maybe they have new endpoints or services we can use. If the response doesn't contain the data anymore, data should come from other endpoint. I'm sure they offer some kind of service we can use.

I don't think selenium is the best way to do this. As you said, it basically means that perceval will have a browser running to process that data.

**Comment by valeriocos** [comment]
This backend isn't related to soft dev. Following the comment at https://github.com/chaoss/grimoirelab-perceval/pull/640#issuecomment-609008667 and considering that this backend may considerably change, it would be wise to:
- create a different repo for backends not strictly related to soft dev
- use this backend as a pilot study for modeling the rules to decide what goes in the core perceval and what doesn't
