### ISSUE TITLE
Error targeting a single space on Confluence

### ISSUE THREAD

**Issue by obaroikoh** [chaoss/grimoirelab-perceval#669]
I am trying to target a single space on confluence. When I run the perceval conmmand using the space's tinyuri, I get the following error. 

command: `perceval confluence "https://wiki.lfnetworking.org/x/UwIiAQ" --from-date '2020-02-01'`

Error:
```[2020-05-19 13:50:23,067] - Sir Perceval is on his quest.
[2020-05-19 13:50:23,073] - Fetching historical contents of 'https://wiki.lfnetworking.org/x/UwIiAQ' from 2020-02-01 00:00:00+00:00
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/perceval/backend.py", line 601, in run
    for item in big.items:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/perceval/backend.py", line 777, in __fetch
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/perceval/backend.py", line 771, in __fetch
    for item in items:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/perceval/backend.py", line 215, in fetch
    for item in self.fetch_items(category, **kwargs):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/perceval/backends/core/confluence.py", line 150, in fetch_items
    contents = [content for content in contents]
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/perceval/backends/core/confluence.py", line 150, in <listcomp>
    contents = [content for content in contents]
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/perceval/backends/core/confluence.py", line 263, in __fetch_contents_summary
    for page in self.client.contents(from_date=from_date):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/perceval/backends/core/confluence.py", line 401, in contents
    for response in self._call(resource, params):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/perceval/backends/core/confluence.py", line 435, in _call
    r = self.fetch(url, payload=params)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/perceval/client.py", line 132, in fetch
    response = self._fetch_from_remote(url, payload, headers, method, stream, verify, auth)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/perceval/client.py", line 173, in _fetch_from_remote
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/perceval/client.py", line 168, in _fetch_from_remote
    response.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error:  for url: https://wiki.lfnetworking.org/pages/tinyurl.action?urlIdentifier=UwIiAQ/rest/api/content/search

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/perceval", line 157, in <module>
    main()
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/perceval", line 103, in main
    cmd.run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/perceval/backend.py", line 611, in run
    raise RuntimeError(str(e))
RuntimeError: 404 Client Error:  for url: https://wiki.lfnetworking.org/pages/tinyurl.action?urlIdentifier=UwIiAQ/rest/api/content/search
```
Is there a way to handle data retrieval using the tinyuri for a given space?

**Comment by valeriocos** [comment]
Hi @obaroikoh , thank you for using Perceval.

Perceval doesn't support fetching a specific space, please try with the following command:
```
confluence https://wiki.lfnetworking.org --from-date 2020-02-01
```

**Comment by obaroikoh** [comment]
> Perceval doesn't support fetching a specific space, please try with the following command:
> 
> ```
> confluence https://wiki.lfnetworking.org --from-date 2020-02-01
> ```

Hi @valeriocos, Thanks for the feedback. The command in your response works, I was just hoping we could directly target a space.

**Comment by valeriocos** [comment]
You're welcome @obaroikoh ! One of the key principle of Perceval is to retrieve all possible information from a given repository and delegate other tasks (processing and filtering) to other GrimoireLab components (e.g., ELK and Kibiter).

Let's close this issue, feel free to reopen it if needed, thanks
