### ISSUE TITLE
[Perceval] - cannot install -pip3 related issues - at worked just fine a few days ago

### ISSUE THREAD

**Issue by lukaszgryglicki** [chaoss/grimoirelab-perceval#685]
Same commands were just working (with pip3 related warning) few days ago:
Either `python3 -m pip install -e "repos/grimoirelab-perceval"` or `pip3 install -e "repos/grimoirelab-perceval"` - both fail:
```
INSTALLING grimoirelab-perceval
Obtaining file:///repos/grimoirelab-perceval
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/repos/grimoirelab-perceval/setup.py'"'"'; __file__='"'"'/repos/grimoirelab-perceval/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-lwgtul9n
         cwd: /repos/grimoirelab-perceval/
    Complete output (47 lines):
        ERROR: Command errored out with exit status 1:
         command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-064sczy6/pandoc/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-064sczy6/pandoc/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-047e99c4
             cwd: /tmp/pip-wheel-064sczy6/pandoc/
        Complete output (11 lines):
        /usr/local/lib/python3.5/dist-packages/_distutils_hack/__init__.py:30: UserWarning: Setuptools is replacing distutils.
          warnings.warn("Setuptools is replacing distutils.")
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/tmp/pip-wheel-064sczy6/pandoc/setup.py", line 65, in <module>
            metadata = about.get_metadata(about_pandoc)
          File "/tmp/pip-wheel-064sczy6/pandoc/.lib/about/__init__.py", line 133, in get_metadata
            README_rst = to_rst(README)
          File "/tmp/pip-wheel-064sczy6/pandoc/.lib/about/__init__.py", line 21, in to_rst
            pandoc = distutils.spawn.find_executable("pandoc")
        AttributeError: module 'distutils' has no attribute 'spawn'
        ----------------------------------------
    ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/setuptools/installer.py", line 126, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/usr/lib/python3.5/subprocess.py", line 271, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp4gmzu3e_', '--quiet', 'pandoc']' returned non-zero exit status 1
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/repos/grimoirelab-perceval/setup.py", line 113, in <module>
        zip_safe=False)
      File "/usr/local/lib/python3.5/dist-packages/setuptools/__init__.py", line 152, in setup
        _install_setup_requires(attrs)
      File "/usr/local/lib/python3.5/dist-packages/setuptools/__init__.py", line 147, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/usr/local/lib/python3.5/dist-packages/setuptools/dist.py", line 676, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 766, in resolve
        replace_conflicting=replace_conflicting
      File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 1049, in best_match
        return self.obtain(req, installer)
      File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 1061, in obtain
        return installer(requirement)
      File "/usr/local/lib/python3.5/dist-packages/setuptools/dist.py", line 732, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/usr/local/lib/python3.5/dist-packages/setuptools/installer.py", line 128, in fetch_build_egg
        raise DistutilsError(str(e)) from e
    distutils.errors.DistutilsError: Command '['/usr/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp4gmzu3e_', '--quiet', 'pandoc']' returned non-zero exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
The command '/bin/sh -c provision/provision.sh' returned a non-zero code: 1
```

**Comment by sduenas** [comment]
I think the problem is related to this issue: https://github.com/pypa/setuptools/issues/2355#issuecomment-685159580 that also raised the errors on #688.

**Comment by lukaszgryglicki** [comment]
Probably, this fixes the issue:
```
#!/usr/bin/env bash
set -eo pipefail
export SETUPTOOLS_USE_DISTUTILS=stdlib
pip3 install --upgrade setuptools
pip3 install --upgrade pip
pip3 install emoji
pip3 install --upgrade requests

repos=(grimoirelab-perceval grimoirelab-elk grimoirelab-sortinghat grimoirelab-kingarthur)

for r in "${repos[@]}"; do
  echo "INSTALLING ${r}"
  # python3 -m pip install -e "${REPOS_DIR}/$r";
  pip3 install -e "${REPOS_DIR}/$r";
done

pip3 install geopy==2.0.0
pip3 install six==1.12.0
```
