### ISSUE TITLE
Current 'dulwich' version doesn't work with Python 3.8

### ISSUE THREAD

**Issue by jjmerchante** [chaoss/grimoirelab-perceval#687]
Using the version of `dulwich` specified in the requirements.txt and running Perceval with Python 3.8 raises the following error:

```
bin/perceval git --latest-items  https://github.com/chaoss/grimoirelab-perceval.git
[2020-09-02 14:34:19,263] - Sir Perceval is on his quest.
[2020-09-02 14:34:19,264] - Fetching latest commits: 'https://github.com/chaoss/grimoirelab-perceval.git' git repository
Traceback (most recent call last):
  File "/home/jjmerchante/.pyenv/versions/perceval/lib/python3.8/site-packages/perceval/backend.py", line 618, in run
    for item in big.items:
  File "/home/jjmerchante/.pyenv/versions/perceval/lib/python3.8/site-packages/perceval/backend.py", line 794, in __fetch
    raise e
  File "/home/jjmerchante/.pyenv/versions/perceval/lib/python3.8/site-packages/perceval/backend.py", line 788, in __fetch
    for item in items:
  File "/home/jjmerchante/.pyenv/versions/perceval/lib/python3.8/site-packages/perceval/backend.py", line 226, in fetch
    for item in self.fetch_items(category, **kwargs):
  File "/home/jjmerchante/.pyenv/versions/perceval/lib/python3.8/site-packages/perceval/backends/core/git.py", line 160, in fetch_items
    commits = self.__fetch_from_repo(from_date, to_date, branches,
  File "/home/jjmerchante/.pyenv/versions/perceval/lib/python3.8/site-packages/perceval/backends/core/git.py", line 279, in __fetch_from_repo
    commits = self.__fetch_newest_commits_from_repo(repo)
  File "/home/jjmerchante/.pyenv/versions/perceval/lib/python3.8/site-packages/perceval/backends/core/git.py", line 316, in __fetch_newest_commits_from_repo
    hashes = repo.sync()
  File "/home/jjmerchante/.pyenv/versions/perceval/lib/python3.8/site-packages/perceval/backends/core/git.py", line 937, in sync
    pack_name, refs = self._fetch_pack()
  File "/home/jjmerchante/.pyenv/versions/perceval/lib/python3.8/site-packages/perceval/backends/core/git.py", line 1105, in _fetch_pack
    client, repo_path = dulwich.client.get_transport_and_path(self.uri)
  File "/home/jjmerchante/.pyenv/versions/perceval/lib/python3.8/site-packages/dulwich/client.py", line 1471, in get_transport_and_path
    return get_transport_and_path_from_url(location, **kwargs)
  File "/home/jjmerchante/.pyenv/versions/perceval/lib/python3.8/site-packages/dulwich/client.py", line 1450, in get_transport_and_path_from_url
    return HttpGitClient.from_parsedurl(
  File "/home/jjmerchante/.pyenv/versions/perceval/lib/python3.8/site-packages/dulwich/client.py", line 1226, in from_parsedurl
    auth, host = urllib2.splituser(parsedurl.netloc)
AttributeError: module 'urllib.request' has no attribute 'splituser'
```

The bug is in the `dulwich` package but it was fixed some years ago and the latest version works with Perceval (all tests pass and the bug is fixed). 

I have seen that you freeze the version of `dulwich` due to a bug with the version `0.19` with a Gerrit URL (https://github.com/chaoss/grimoirelab-perceval/issues/369), I tested one from gerrit.googlesource.com but I didn't get any error.

Can I create a Pull request or the version should be < 0.19?

**Comment by sduenas** [comment]
Sure, feel free to do it.
