### ISSUE TITLE
Command line client displays RuntimeError traceback

### ISSUE THREAD

**Issue by sduenas** [chaoss/grimoirelab-perceval#692]
When a backend fails the command line client crashes and prints the whole traceback with the error. The client should terminate showing an error but not the whole traceback. The traceback should only be shown when the program is run with the debug flag (`-g`).

This is an example with one of the most common errors, so you can reproduce the problem fast:
```
$ perceval github chaoss grimoirelab-perceval --no-archiv3
[...]
Traceback (most recent call last):
  File "/home/sduenas/devel/grimoirelab/perceval/perceval/backend.py", line 618, in run
    for item in big.items:
  File "/home/sduenas/devel/grimoirelab/perceval/perceval/backend.py", line 794, in __fetch
    raise e
  File "/home/sduenas/devel/grimoirelab/perceval/perceval/backend.py", line 788, in __fetch
    for item in items:
  File "/home/sduenas/devel/grimoirelab/perceval/perceval/backend.py", line 226, in fetch
    for item in self.fetch_items(category, **kwargs):
  File "/home/sduenas/devel/grimoirelab/perceval/perceval/backends/core/github.py", line 320, in __fetch_issues
    issue[field + '_data'] = self.__get_issue_comments(issue['number'])
  File "/home/sduenas/devel/grimoirelab/perceval/perceval/backends/core/github.py", line 393, in __get_issue_comments
    for raw_comments in group_comments:
  File "/home/sduenas/devel/grimoirelab/perceval/perceval/backends/core/github.py", line 882, in fetch_items
    response = self.fetch(url_next, payload=payload)
  File "/home/sduenas/devel/grimoirelab/perceval/perceval/backends/core/github.py", line 862, in fetch
    self.sleep_for_rate_limit()
  File "/home/sduenas/devel/grimoirelab/perceval/perceval/client.py", line 279, in sleep_for_rate_limit
    raise RateLimitError(cause=cause, seconds_to_reset=seconds_to_reset)
perceval.errors.RateLimitError: Rate limit exhausted.; 3588.0 seconds to rate reset

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sduenas/devel/venv/bin/perceval", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/sduenas/devel/grimoirelab/perceval/bin/perceval", line 169, in <module>
    main()
  File "/home/sduenas/devel/grimoirelab/perceval/bin/perceval", line 115, in main
    cmd.run()
  File "/home/sduenas/devel/grimoirelab/perceval/perceval/backend.py", line 630, in run
    raise RuntimeError(str(e))
RuntimeError: Rate limit exhausted.; 3588.0 seconds to rate reset

```

**Comment by AllMight2099** [comment]
Hey there! Can I take this issue up if no one's working on it?

**Comment by vchrombie** [comment]
@AllMight2099, no one has been assigned so far. Please feel free to take it up and open a PR.

**Comment by AllMight2099** [comment]
@sduenas @vchrombie 
Hey there! I fixed it by passing in a bool flag (`debug_check`) in the constructor for the `BackendCommand` class. While raising the exception, I'm setting `logger` exception's function parameter (`exc_info=debug_check`). This prevents the stack trace from getting printed when not in debug mode


> The traceback should only be shown when the program is run with the debug flag (`-d`).

Also, is the debug flag `-d` or `-g`? cause the issue states that it's the former

**Comment by sduenas** [comment]
> @sduenas @vchrombie
> Hey there! I fixed it by passing in a bool flag (`debug_check`) in the constructor for the `BackendCommand` class. While raising the exception, I'm setting `logger` exception's function parameter (`exc_info=debug_check`). This prevents the stack trace from getting printed when not in debug mode
> 
> > The traceback should only be shown when the program is run with the debug flag (`-d`).
> 
> Also, is the debug flag `-d` or `-g`? cause the issue states that it's the former

The flag should be `-g`. I made a typo. I'll change the description.
