### ISSUE TITLE
Problem parsing dates in pipermail

### ISSUE THREAD

**Issue by acs** [chaoss/grimoirelab-perceval#74]
```
(acs@dellx) (master *$% u=) ~/devel/GrimoireELK/utils $ ./p2o.py -g -e http://localhost:9200 pipermail https://mail.python.org/pipermail/cplusplus-sig/
....
2016-10-10 20:11:03,411 Message bogus@does.not.exist.com  Tue Oct 14 00:29:20 2008 parsed
2016-10-10 20:11:03,412 Error feeding ocean from pipermail (https://mail.python.org/pipermail/cplusplus-sig/): Fri, 24 May 2002 00.24.50 +0200 is not a valid date
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.3.2.dev0-py3.5.egg/perceval/utils.py", line 119, in str_to_datetime
    dt = dateutil.parser.parse(ts)
  File "/usr/lib/python3/dist-packages/dateutil/parser.py", line 1008, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/usr/lib/python3/dist-packages/dateutil/parser.py", line 395, in parse
    raise ValueError("Unknown string format")
ValueError: Unknown string format
```

**Comment by acs** [comment]
Any updates on this @sduenas ?

**Comment by sduenas** [comment]
We didn't find this error nor anybody complained about it.
