### ISSUE TITLE
[github] TypeError fetching a reaction

### ISSUE THREAD

**Issue by zhquan** [chaoss/grimoirelab-perceval#746]
We have an error fetching this issue https://github.com/golang/go/issues/18802#issuecomment-371433982 due to one of the reactions has not user content
```
$ curl -H "Accept: application/vnd.github.squirrel-girl-preview+json" 'https://api.github.com/repos/golang/go/issues/comments/675920268/reactions'
[
  ...
  {
    "id": 20632567,
    "node_id": "MDg6UmVhY3Rpb24yMDYzMjU2Nw==",
    "user": null,
    "content": "heart",
    "created_at": "2018-03-09T10:46:13Z"
  },
  ...
]
```
The error:
```
$ perceval github golang go --from-date 2020-08-30T02:18:00+02:00 -t xxx --sleep-for-rate                                                                                 
[2021-08-02 20:09:22,518] - Sir Perceval is on his quest.
[2021-08-02 20:09:42,914] - Error!: 'NoneType' object is not subscriptable
[2021-08-02 20:09:42,917] - Sir Perceval completed his quest.
```
Using [SirMordred](https://github.com/chaoss/grimoirelab-sirmordred)
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/grimoire_elk/elk.py", line 162, in feed_backend
    ocean_backend.feed(**params)
  File "/usr/local/lib/python3.7/dist-packages/grimoire_elk/raw/elastic.py", line 228, in feed
    self.feed_items(items)
  File "/usr/local/lib/python3.7/dist-packages/grimoire_elk/raw/elastic.py", line 244, in feed_items
    for item in items:
  File "/usr/local/lib/python3.7/dist-packages/perceval/backend.py", line 226, in feed
    for item in self.fetch_items(category, **kwargs):
  File "/usr/local/lib/python3.7/dist-packages/perceval/backends/core/github.py", line 330, in __fetch_issues
    issue[field + '_data'] = self.__get_issue_comments(issue['number'])
  File "/usr/local/lib/python3.7/dist-packages/perceval/backends/core/github.py", line 409, in __get_issue_comments
    self.__get_issue_comment_reactions(comment_id, comment['reactions']['total_count'])
  File "/usr/local/lib/python3.7/dist-packages/perceval/backends/core/github.py", line 427, in __get_issue_comment_reactions
    reaction['user_data'] = self.__get_user(reaction['user']['login'])
TypeError: 'NoneType' object is not subscriptable
```

**Comment by vchrombie** [comment]
Interesting, do you know how this can occur?

I'm guessing when the user posts a reaction to the comment and later deletes the account. Do you think there is any other scenario?

For comments, usually, it redirects to the @ghost AFAIK. I think reactions don't support this yet.
