### ISSUE TITLE
[jira] Not clear error when running wrong URLs in Jira

### ISSUE THREAD

**Issue by dicortazar** [chaoss/grimoirelab-perceval#88]
Hi, 

I've tried to run Perceval on Jira. After a while I realized that the error was related to a wrong URL I was using.

However, the error is not captured and it's not clear what that means until you use the debug mode in Perceval. I would expect some clearer message error without using the debug option.

Error and how to reproduce this:

```bash

$ perceval -g jira 'https://issues.apache.org' --project PIG

[2016-10-28 12:11:39,324 - root - INFO] - Sir Perceval is on his quest.
[2016-10-28 12:11:39,328 - perceval.backends.jira - INFO] - Looking for issues at site 'https://issues.apache.org', in project 'PIG' and updated from '1970-01-01 00:00:00+00:00'
[2016-10-28 12:11:39,331 - requests.packages.urllib3.connectionpool - INFO] - Starting new HTTPS connection (1): issues.apache.org
[2016-10-28 12:11:40,152 - requests.packages.urllib3.connectionpool - DEBUG] - "GET /rest/api/2/field HTTP/1.1" 404 214
Traceback (most recent call last):
  File "/usr/local/bin/perceval", line 4, in <module>
    **import**('pkg_resources').run_script('perceval==0.4.0.dev1', 'perceval')
  File "/usr/lib/python3/dist-packages/pkg_resources/**init**.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/**init**.py", line 1652, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.4.0.dev1-py3.4.egg/EGG-INFO/scripts/perceval", line 176, in <module>
    main()
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.4.0.dev1-py3.4.egg/EGG-INFO/scripts/perceval", line 97, in main
    cmd.run()
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.4.0.dev1-py3.4.egg/perceval/backends/jira.py", line 408, in run
    raise requests.exceptions.HTTPError(str(e.response.json()))
  File "/usr/lib/python3/dist-packages/requests/models.py", line 819, in json
    return json.loads(self.text, **kwargs)
  File "/usr/lib/python3.4/json/**init**.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)

```

**Comment by sduenas** [comment]
This is already fixed. The current output is:

```
$ perceval jira 'https://issues.apache.org' --project PIG
[2023-04-27 12:08:16,819] - Sir Perceval is on his quest.
[2023-04-27 12:08:16,862] - Looking for issues at site 'https://issues.apache.org', in project 'PIG' and updated from '1970-01-01 00:00:00+00:00'
[2023-04-27 12:08:17,054] - Error!: 404 Client Error: Not Found for url: https://issues.apache.org/rest/api/2/field
[2023-04-27 12:08:17,056] - Sir Perceval completed his quest.

```
